/*
 * Decompiled with CFR 0.152.
 */
package helden.framework.D;

import java.util.HashMap;

public class S {
    private HashMap<String, String> o00000;

    public S() {
        this.Object();
        this.o00000();
        this.\u00d200000();
    }

    public String o00000(String string) {
        if (this.o00000.get(string) != null) {
            return this.o00000.get(string);
        }
        if (string.startsWith("Talentspezialisierung")) {
            return "TS " + string.substring(21);
        }
        return string;
    }

    private void Object() {
        this.o00000 = new HashMap();
        this.o00000.put("Druidisches Dolchritual: Bann", "Dolch: Bann");
        this.o00000.put("Druidisches Dolchritual: Ernte", "Dolch: Ernte");
        this.o00000.put("Druidisches Dolchritual: Gesp\u00fcr", "Dolch: Gesp\u00fcr");
        this.o00000.put("Druidisches Dolchritual: Lebenskraft", "Dolch: Lebenskraft");
        this.o00000.put("Druidisches Dolchritual: Leib", "Dolch: Leib");
        this.o00000.put("Druidisches Dolchritual: Licht", "Dolch: Licht");
        this.o00000.put("Druidisches Dolchritual: Opferdolch", "Dolch: Opferdolch");
        this.o00000.put("Druidisches Dolchritual: Schneide", "Dolch: Schneide");
        this.o00000.put("Druidisches Dolchritual: Schutz", "Dolch: Schutz");
        this.o00000.put("Druidisches Dolchritual: Weg", "Dolch: Weg");
        this.o00000.put("Druidisches Dolchritual: Weihe", "Dolch: Weihe");
        this.o00000.put("Druidisches Dolchritual: Weisung", "Dolch: Weisung");
        this.o00000.put("Druidisches Herrschaftsritual: Amulett der Herrschaft", "DHR: Amulett der Herrschaft");
        this.o00000.put("Druidisches Herrschaftsritual: Kristall der Herrschaft", "DHR: Kristall der Herrschaft");
        this.o00000.put("Druidisches Herrschaftsritual: Miniatur der Herrschaft", "DHR: Miniatur der Herrschaft");
        this.o00000.put("Druidisches Herrschaftsritual: Wachs der Herrschaft", "DHR: Wachs der Herrschaft");
        this.o00000.put("Druidisches Herrschaftsritual: Wurzel des Blutes", "DHR: Wurzel des Blutes");
        this.o00000.put("Elfenlied: Erinnerungsmelodie", "EL: Erinnerungsmelodie");
        this.o00000.put("Elfenlied: Freundschaftslied", "EL: Freundschaftslied");
        this.o00000.put("Elfenlied: Friedenslied", "EL: Friedenslied");
        this.o00000.put("Elfenlied: Lied der Lieder", "EL: Lied der Lieder");
        this.o00000.put("Elfenlied: Lied der Reinheit", "EL: Lied der Reinheit");
        this.o00000.put("Elfenlied: Lied des Trostes", "EL: Lied des Trostes");
        this.o00000.put("Elfenlied: Melodie der Kunstfertigkeit", "EL: Mel. d. Kunstfertigkeit");
        this.o00000.put("Elfenlied: Sorgenlied", "EL: Sorgenlied");
        this.o00000.put("Elfenlied: Windgefl\u00fcster", "EL: Windgefl\u00fcster");
        this.o00000.put("Elfenlied: Zaubermelodie", "EL: Zaubermelodie");
        this.o00000.put("Gabe des Od\u00fbn: Blut des Od\u00fbn", "Od\u00fbn: Blut des Od\u00fbn");
        this.o00000.put("Gabe des Od\u00fbn: Haut des Od\u00fbn", "Od\u00fbn: Haut des Od\u00fbn");
        this.o00000.put("Gabe des Od\u00fbn: Ruf des Od\u00fbn", "Od\u00fbn: Ruf des Od\u00fbn");
        this.o00000.put("Gabe des Od\u00fbn: Seele des Od\u00fbn", "Od\u00fbn: Seele des Od\u00fbn");
        this.o00000.put("Gabe des Od\u00fbn: Hauch des Od\u00fbn", "Od\u00fbn: Hauch des Od\u00fbn");
        this.o00000.put("Hexenfluch: \u00c4ngste mehren", "HF: \u00c4ngste mehren");
        this.o00000.put("Hexenfluch: Bei\u00df auf Granit", "HF: Bei\u00df auf Granit");
        this.o00000.put("Hexenfluch: Beute", "HF: Beute");
        this.o00000.put("Hexenfluch: Hagelschlag", "HF: Hagelschlag");
        this.o00000.put("Hexenfluch: Hexenschuss", "HF: Hexenschuss");
        this.o00000.put("Hexenfluch: Kornf\u00e4ule", "HF: Kornf\u00e4ule");
        this.o00000.put("Hexenfluch: Kr\u00f6tenkuss", "HF: Kr\u00f6tenkuss");
        this.o00000.put("Hexenfluch: Mit Blindheit schlagen", "HF: Mit Blindheit schlagen");
        this.o00000.put("Hexenfluch: Pech an den Hals", "HF: Pech an den Hals");
        this.o00000.put("Hexenfluch: Pestilenz", "HF: Pestilenz");
        this.o00000.put("Hexenfluch: Schlaf rauben", "HF: Schlaf rauben");
        this.o00000.put("Hexenfluch: Todesfluch", "HF: Todesfluch");
        this.o00000.put("Hexenfluch: Unfruchtbarkeit", "HF: Unfruchtbarkeit");
        this.o00000.put("Hexenfluch: Viehverst\u00fcmmelung", "HF: Viehverst\u00fcmmelung");
        this.o00000.put("Hexenfluch: Warzen sprie\u00dfen", "HF: Warzen sprie\u00dfen");
        this.o00000.put("Hexenfluch: Zunge l\u00e4hmen", "HF: Zunge l\u00e4hmen");
        this.o00000.put("Keulenritual: Apport der Keule", "KR: Apport der Keule");
        this.o00000.put("Keulenritual: Bann der Keule", "KR: Bann der Keule");
        this.o00000.put("Keulenritual: Geist der Keule", "KR: Geist der Keule");
        this.o00000.put("Keulenritual: Gesp\u00fcr der Keule", "KR: Gesp\u00fcr der Keule");
        this.o00000.put("Keulenritual: H\u00e4rte der Keule", "KR: H\u00e4rte der Keule");
        this.o00000.put("Keulenritual: Hilfe der Keule", "KR: Hilfe der Keule");
        this.o00000.put("Keulenritual: Kraft der Keule", "KR: Kraft der Keule");
        this.o00000.put("Keulenritual: N\u00e4he zur Natur", "KR: N\u00e4he zur Natur");
        this.o00000.put("Keulenritual: Opferkeule", "KR: Opferkeule");
        this.o00000.put("Keulenritual: Weihe der Keule", "KR: Weihe der Keule");
        this.o00000.put("Keulenritual: Zauber der Keule", "KR: Zauber der Keule");
        this.o00000.put("Kristallomantisches Ritual: Kristallbindung", "Kristall: Kristallbindung");
        this.o00000.put("Kristallomantisches Ritual: Kristallformung", "Kristall: Kristallformung");
        this.o00000.put("Kristallomantisches Ritual: Madakristall", "Kristall: Madakristall");
        this.o00000.put("Kristallomantisches Ritual: Matrixkristall", "Kristall: Matrixkristall");
        this.o00000.put("Kristallomantisches Ritual: Thesiskristall", "Kristall: Thesiskristall");
        this.o00000.put("Kugelzauber: Bildergalerie", "KuZ: Bildergalerie");
        this.o00000.put("Kugelzauber: Bilderspiel", "KuZ: Bilderspiel");
        this.o00000.put("Kugelzauber: Bindung", "KuZ: Bindung");
        this.o00000.put("Kugelzauber: Brennglas und Prisma", "KuZ: Brennglas und Prisma");
        this.o00000.put("Kugelzauber: Farben des Geistes", "KuZ: Farben des Geistes");
        this.o00000.put("Kugelzauber: Fernbild", "KuZ: Fernbild");
        this.o00000.put("Kugelzauber: H'Szints Auge", "KuZ: H'Szints Auge");
        this.o00000.put("Kugelzauber: Kugel der Illusionisten", "KuZ: Kugel der Illusionisten");
        this.o00000.put("Kugelzauber: Kugel des Hellsehers", "KuZ: Kugel des Hellsehers");
        this.o00000.put("Kugelzauber: Orbitarium", "KuZ: Orbitarium");
        this.o00000.put("Kugelzauber: Schutz gegen Untote", "KuZ: Schutz gegen Untote");
        this.o00000.put("Kugelzauber: Wachendes Auge", "KuZ: Wachendes Auge");
        this.o00000.put("Kugelzauber: Warnendes Leuchten", "KuZ: Warnendes Leuchten");
        this.o00000.put("Liturgie: 12 Segnungen", "Lit: 12 Segnungen");
        this.o00000.put("Liturgie: F\u00fcnfte Lobpreisung des Fr\u00fchlings", "Lit: 5. Lobpreisung d. Fr\u00fchlings");
        this.o00000.put("Liturgie: Achmad'ayan ankhrella al'nurach Shaitanim", "Lit: Achmad'ayan ankhrella ...");
        this.o00000.put("Liturgie: Aller Welt Freund", "Lit: Aller Welt Freund");
        this.o00000.put("Liturgie: Allmacht der Lohe", "Lit: Allmacht der Lohe");
        this.o00000.put("Liturgie: Alte Schuppen", "Lit: Alte Schuppen");
        this.o00000.put("Liturgie: Am Busen der Natur", "Lit: Am Busen der Natur");
        this.o00000.put("Liturgie: Anathema", "Lit: Anathema");
        this.o00000.put("Liturgie: Angroschs Opfergabe", "Lit: Angroschs Opfergabe");
        this.o00000.put("Liturgie: Angroschs Zorn", "Lit: Angroschs Zorn");
        this.o00000.put("Liturgie: Anrufug der Erdkraft", "Lit: Anrufug der Erdkraft");
        this.o00000.put("Liturgie: Anrufung der Winde", "Lit: Anrufung der Winde");
        this.o00000.put("Liturgie: Anrufung Nuiannas", "Lit: Anrufung Nuiannas");
        this.o00000.put("Liturgie: Arcanum Interdictum", "Lit: Arcanum Interdictum");
        this.o00000.put("Liturgie: Argelions bannende Hand", "Lit: Argelions bannende Hand");
        this.o00000.put("Liturgie: Argelions Mantel", "Lit: Argelions Mantel");
        this.o00000.put("Liturgie: Argelions Spiegel", "Lit: Argelions Spiegel");
        this.o00000.put("Liturgie: Ascandears Hingabe", "Lit: Ascandears Hingabe");
        this.o00000.put("Liturgie: Auge der wartenden Seelen", "Lit: Auge d. wartenden Seelen");
        this.o00000.put("Liturgie: Auge des H\u00e4ndlers", "Lit: Auge des H\u00e4ndlers");
        this.o00000.put("Liturgie: Auge des Mondes", "Lit: Auge des Mondes");
        this.o00000.put("Liturgie: Aura der Form", "Lit: Aura der Form");
        this.o00000.put("Liturgie: Aura des Regenbogens", "Lit: Aura des Regenbogens");
        this.o00000.put("Liturgie: Azilas Quellgesang", "Lit: Azilas Quellgesang");
        this.o00000.put("Liturgie: Bann der Geisterkr\u00e4fte", "Lit: Bann der Geisterkr\u00e4fte");
        this.o00000.put("Liturgie: Bann des Heiligen Khalid", "Lit: Bann des Heiligen Khalid");
        this.o00000.put("Liturgie: Begehen der Heiligen Wasser", "Lit: Begehen der Hlg. Wasser");
        this.o00000.put("Liturgie: Belemans Hochzeit", "Lit: Belemans Hochzeit");
        this.o00000.put("Liturgie: Bindung der Schlange", "Lit: Bindung der Schlange");
        this.o00000.put("Liturgie: Bishdariels Angesicht", "Lit: Bishdariels Angesicht");
        this.o00000.put("Liturgie: Bishdariels Auge", "Lit: Bishdariels Auge");
        this.o00000.put("Liturgie: Bishdariels Warnung", "Lit: Bishdariels Warnung");
        this.o00000.put("Liturgie: Blendstrahl aus Alveran", "Lit: Blendstrahl aus Alveran");
        this.o00000.put("Liturgie: Blick auf das Geisterwesen", "Lit: Blick a.d. Geisterwesen");
        this.o00000.put("Liturgie: Blick an den klaren Himmel", "Lit: Blick a.d. klaren Himmel");
        this.o00000.put("Liturgie: Blick durch Tairachs Augen", "Lit: Blick d. Tairachs Augen");
        this.o00000.put("Liturgie: Blick der Weberin", "Lit: Blick der Weberin");
        this.o00000.put("Liturgie: Blick f\u00fcr das Handwerk", "Lit: Blick f\u00fcr das Handwerk");
        this.o00000.put("Liturgie: Blick in die Erinnerung", "Lit: Blick in die Erinnerung");
        this.o00000.put("Liturgie: Blick in die Flammen", "Lit: Blick in die Flammen");
        this.o00000.put("Liturgie: Bootssegen", "Lit: Bootssegen");
        this.o00000.put("Liturgie: Borons s\u00fc\u00dfe Gnade", "Lit: Borons s\u00fc\u00dfe Gnade");
        this.o00000.put("Liturgie: Buchpr\u00fcfung", "Lit: Buchpr\u00fcfung");
        this.o00000.put("Liturgie: Cereborns Handreichung", "Lit: Cereborns Handreichung");
        this.o00000.put("Liturgie: Daradors Bann der Schatten", "Lit: Daradors Bann d. Schatten");
        this.o00000.put("Liturgie: Daradors pr\u00fcfender Blick", "Lit: Daradors pr\u00fcfender Blick");
        this.o00000.put("Liturgie: Der G\u00e4nsemutter warmes Nest", "Lit: Der G\u00e4nsemutter warmes..");
        this.o00000.put("Liturgie: Des Herren Goldener Mittag", "Lit: Des Herren Goldener ..");
        this.o00000.put("Liturgie: Dorlens Verbr\u00fcderung", "Lit: Dorlens Verbr\u00fcderung");
        this.o00000.put("Liturgie: Dreifacher Saatsegen", "Lit: Dreifacher Saatsegen");
        this.o00000.put("Liturgie: Dythlinds Wandeln im Feuer", "Lit: Dythlinds Wandeln i. Feuer");
        this.o00000.put("Liturgie: Efferdsegen", "Lit: Efferdsegen");
        this.o00000.put("Liturgie: Eherne Kraft - lodernder Zorn", "Lit: Eherne Kraft - lod. Zorn");
        this.o00000.put("Liturgie: Ehrenhafter Zweikampf", "Lit: Ehrenhafter Zweikampf");
        this.o00000.put("Liturgie: Eidechsenhaut", "Lit: Eidechsenhaut");
        this.o00000.put("Liturgie: Eidsegen", "Lit: Eidsegen");
        this.o00000.put("Liturgie: Ein Bild f\u00fcr die Ewigkeit", "Lit: Ein Bild f\u00fcr die Ewigkeit");
        this.o00000.put("Liturgie: Ein Freund in Zeiten der Not", "Lit: Ein Freund in Zeiten d. Not");
        this.o00000.put("Liturgie: Elementwandlung", "Lit: Elementwandlung");
        this.o00000.put("Liturgie: Entzug des Wissens", "Lit: Entzug des Wissens");
        this.o00000.put("Liturgie: Entzug von Nandus' Gaben", "Lit: Entzug v. Nandus' Gaben");
        this.o00000.put("Liturgie: Erl\u00f6sung des Tapams", "Lit: Erl\u00f6sung des Tapams");
        this.o00000.put("Liturgie: Erneuerung des Geborstenen", "Lit: Erneuerung d. Geborstenen");
        this.o00000.put("Liturgie: Etilias Gnade", "Lit: Etilias Gnade");
        this.o00000.put("Liturgie: Etilias Zeit der Meditation", "Lit: Etilias Zeit der Meditation");
        this.o00000.put("Liturgie: Ewiger W\u00e4chter", "Lit: Ewiger W\u00e4chter");
        this.o00000.put("Liturgie: Ewiges Wissen", "Lit: Ewiges Wissen");
        this.o00000.put("Liturgie: Exkommunikation", "Lit: Exkommunikation");
        this.o00000.put("Liturgie: Exorzismus", "Lit: Exorzismus");
        this.o00000.put("Liturgie: Feuersegen", "Lit: Feuersegen");
        this.o00000.put("Liturgie: Feuertaufe", "Lit: Feuertaufe");
        this.o00000.put("Liturgie: Firuns Einsicht", "Lit: Firuns Einsicht");
        this.o00000.put("Liturgie: Flagge des Regenbogens", "Lit: Flagge des Regenbogens");
        this.o00000.put("Liturgie: Freundliche Aufnahme", "Lit: Freundliche Aufnahme");
        this.o00000.put("Liturgie: Frieden der Melodie", "Lit: Frieden der Melodie");
        this.o00000.put("Liturgie: F\u00fcrbitten des Heiligen Theb\u00fbn", "Lit: F\u00fcrbitten des Hlg. Theb\u00fbn");
        this.o00000.put("Liturgie: Garafans Glei\u00dfende Schwingen", "Lit: Garafans Glei\u00dfende Schw..");
        this.o00000.put("Liturgie: Gebieter der Lava", "Lit: Gebieter der Lava");
        this.o00000.put("Liturgie: Geburtssegen", "Lit: Geburtssegen");
        this.o00000.put("Liturgie: Geistermantel", "Lit: Geistermantel");
        this.o00000.put("Liturgie: Gel\u00e4utert sei Erz und Goldgestein", "Lit: Gel\u00e4utert sei Erz..");
        this.o00000.put("Liturgie: Gemeinschaft der treuen Gef\u00e4hrten", "Lit: Gemeinschaft der treuen..");
        this.o00000.put("Liturgie: Gesang der Delphine", "Lit: Gesang der Delphine");
        this.o00000.put("Liturgie: Gesang der Wale", "Lit: Gesang der Wale");
        this.o00000.put("Liturgie: Gesegneter Fang", "Lit: Gesegneter Fang");
        this.o00000.put("Liturgie: Geteiltes Leid", "Lit: Geteiltes Leid");
        this.o00000.put("Liturgie: Gift der Erkenntnis", "Lit: Gift der Erkenntnis");
        this.o00000.put("Liturgie: Gilborns heilige Aura", "Lit: Gilborns heilige Aura");
        this.o00000.put("Liturgie: Gleichklang des Geistes", "Lit: Gleichklang des Geistes");
        this.o00000.put("Liturgie: Gl\u00fcckssegen", "Lit: Gl\u00fcckssegen");
        this.o00000.put("Liturgie: Goldene R\u00fcstung", "Lit: Goldene R\u00fcstung");
        this.o00000.put("Liturgie: Goldener Blick", "Lit: Goldener Blick");
        this.o00000.put("Liturgie: Gorfangs Fluch", "Lit: Gorfangs Fluch");
        this.o00000.put("Liturgie: G\u00f6ttliche Verst\u00e4ndigung", "Lit: G\u00f6ttliche Verst\u00e4ndigung");
        this.o00000.put("Liturgie: G\u00f6ttliches Zeichen", "Lit: G\u00f6ttliches Zeichen");
        this.o00000.put("Liturgie: Grabsegen", "Lit: Grabsegen");
        this.o00000.put("Liturgie: Graues Siegel", "Lit: Graues Siegel");
        this.o00000.put("Liturgie: Grispelz' Ackersegen", "Lit: Grispelz' Ackersegen");
        this.o00000.put("Liturgie: Grispelz' Fruchtbarkeit", "Lit: Grispelz' Fruchtbarkeit");
        this.o00000.put("Liturgie: Gro\u00dfe Seelenwaschung", "Lit: Gro\u00dfe Seelenwaschung");
        this.o00000.put("Liturgie: Gro\u00dfe Weihe des Heimsteins", "Lit: Gro\u00dfe Weihe d. Heimsteins");
        this.o00000.put("Liturgie: Gro\u00dfer Weihesegen der Waffe", "Lit: Gro\u00dfe Weihe der Waffe");
        this.o00000.put("Liturgie: Gro\u00dfer Eidsegen", "Lit: Gro\u00dfer Eidsegen");
        this.o00000.put("Liturgie: Gro\u00dfer Giftbann", "Lit: Gro\u00dfer Giftbann");
        this.o00000.put("Liturgie: Gro\u00dfer Reisesegen", "Lit: Gro\u00dfer Reisesegen");
        this.o00000.put("Liturgie: Gro\u00dfer Speisesegen", "Lit: Gro\u00dfer Speisesegen");
        this.o00000.put("Liturgie: Gro\u00dfes Tabu", "Lit: Gro\u00dfes Tabu");
        this.o00000.put("Liturgie: Gru\u00df des Versunkenen", "Lit: Gru\u00df des Versunkenen");
        this.o00000.put("Liturgie: H\u00e4ndlersegen", "Lit: H\u00e4ndlersegen");
        this.o00000.put("Liturgie: Handwerkssegen", "Lit: Handwerkssegen");
        this.o00000.put("Liturgie: Harmoniesegen", "Lit: Harmoniesegen");
        this.o00000.put("Liturgie: Hashnabiths Flehen", "Lit: Hashnabiths Flehen");
        this.o00000.put("Liturgie: Hauch Borons", "Lit: Hauch Borons");
        this.o00000.put("Liturgie: Hauch der Leidenschaft", "Lit: Hauch der Leidenschaft");
        this.o00000.put("Liturgie: Hausfrieden", "Lit: Hausfrieden");
        this.o00000.put("Liturgie: Haut des Cham\u00e4leons", "Lit: Haut des Cham\u00e4leons");
        this.o00000.put("Liturgie: Heilige Schmiedeglut", "Lit: Heilige Schmiedeglut");
        this.o00000.put("Liturgie: Heiliger Befehl", "Lit: Heiliger Befehl");
        this.o00000.put("Liturgie: Heiliger Lehnseid", "Lit: Heiliger Lehnseid");
        this.o00000.put("Liturgie: Heiliges Liebesspiel", "Lit: Heiliges Liebesspiel");
        this.o00000.put("Liturgie: Heiligung des Tapams", "Lit: Heiligung des Tapams");
        this.o00000.put("Liturgie: Heilungssegen", "Lit: Heilungssegen");
        this.o00000.put("Liturgie: Herr \u00fcber Feuer und Glut", "Lit: Herr \u00fcber Feuer und Glut");
        this.o00000.put("Liturgie: Hesindes Fingerzeig", "Lit: Hesindes Fingerzeig");
        this.o00000.put("Liturgie: Hilfe in der Not", "Lit: Hilfe in der Not");
        this.o00000.put("Liturgie: Heilige Salbung der Peraine", "Lit: Hlg. Salbung der Peraine");
        this.o00000.put("Liturgie: Hoftag der Sprachen", "Lit: Hoftag der Sprachen");
        this.o00000.put("Liturgie: Indoktrination", "Lit: Indoktrination");
        this.o00000.put("Liturgie: Ingerimms Zorn verschone uns", "Lit: ING Zorn verschone uns");
        this.o00000.put("Liturgie: Ingalfs Alchimie", "Lit: Ingalfs Alchimie");
        this.o00000.put("Liturgie: Initiation", "Lit: Initiation");
        this.o00000.put("Liturgie: Innere Ruhe", "Lit: Innere Ruhe");
        this.o00000.put("Liturgie: Jagdgl\u00fcck", "Lit: Jagdgl\u00fcck");
        this.o00000.put("Liturgie: K\u00e4lbchensegen", "Lit: K\u00e4lbchensegen");
    }

    private void o00000() {
        this.o00000.put("Liturgie: Kamaluqs Fluch", "Lit: Kamaluqs Fluch");
        this.o00000.put("Liturgie: Kamaluqs unerbittlicher Speer", "Lit: Kamaluqs unerbittl. Speer");
        this.o00000.put("Liturgie: Khablas Jugend", "Lit: Khablas Jugend");
        this.o00000.put("Liturgie: Khablas makelloser Leib", "Lit: Khablas makelloser Leib");
        this.o00000.put("Liturgie: Kirschbl\u00fctenregen", "Lit: Kirschbl\u00fctenregen");
        this.o00000.put("Liturgie: Kleine Liturgie des Heiligen Nemekath", "Lit: Kl Lit. d. Hlg. Nemekath");
        this.o00000.put("Liturgie: Kleine Segnung des Heimsteins", "Lit: Kl. Segnung d. Heimsteins");
        this.o00000.put("Liturgie: Kleiner Giftbann", "Lit: Kleiner Giftbann");
        this.o00000.put("Liturgie: Kleines Tabu", "Lit: Kleines Tabu");
        this.o00000.put("Liturgie: Konsekration", "Lit: Konsekration");
        this.o00000.put("Liturgie: Kr\u00e4ftigung der Schwachen und Versehrten", "Lit: Kr\u00e4ftigung d. Schwachen");
        this.o00000.put("Liturgie: Kr\u00e4utersegen des Heiligen Nemekath", "Lit: Kr\u00e4uters. d. Hlg. Nemekath");
        this.o00000.put("Liturgie: Lagorax' Hammer rufen", "Lit: Lagorax' Hammer rufen");
        this.o00000.put("Liturgie: Levthans Fesseln", "Lit: Levthans Fesseln");
        this.o00000.put("Liturgie: Licht des Herrn", "Lit: Licht des Herrn");
        this.o00000.put("Liturgie: Licht des verborgenen Pfades", "Lit: Licht des verb. Pfades");
        this.o00000.put("Liturgie: Lohn des Unverzagten", "Lit: Lohn des Unverzagten");
        this.o00000.put("Liturgie: Lug und Trug", "Lit: Lug und Trug");
        this.o00000.put("Liturgie: Mannschaftssegen", "Lit: Mannschaftssegen");
        this.o00000.put("Liturgie: Marbos Geisterblick", "Lit: Marbos Geisterblick");
        this.o00000.put("Liturgie: Marbos Geleit", "Lit: Marbos Geleit");
        this.o00000.put("Liturgie: M\u00e4rtyrersegen", "Lit: M\u00e4rtyrersegen");
        this.o00000.put("Liturgie: Meisterst\u00fcck", "Lit: Meisterst\u00fcck");
        this.o00000.put("Liturgie: Mondsilberzunge", "Lit: Mondsilberzunge");
        this.o00000.put("Liturgie: Nandus Schriftkenntnis", "Lit: Nandus Schriftkenntnis");
        this.o00000.put("Liturgie: Nemekaths Bannfluch", "Lit: Nemekaths Bannfluch");
        this.o00000.put("Liturgie: Nemekaths Geisterblick", "Lit: Nemekaths Geisterblick");
        this.o00000.put("Liturgie: Nemekaths Zwiesprache", "Lit: Nemekaths Zwiesprache");
        this.o00000.put("Liturgie: Neun Streiche in Einem", "Lit: Neun Streiche in Einem");
        this.o00000.put("Liturgie: Nimmerm\u00fcde Wanderschaft", "Lit: Nimmerm\u00fcde Wandersch.");
        this.o00000.put("Liturgie: Noionas Zuspruch", "Lit: Noionas Zuspruch");
        this.o00000.put("Liturgie: Obarans Bannstrahl", "Lit: Obarans Bannstrahl");
        this.o00000.put("Liturgie: Objektsegen", "Lit: Objektsegen");
        this.o00000.put("Liturgie: Objektweihe", "Lit: Objektweihe");
        this.o00000.put("Liturgie: Ordination", "Lit: Ordination");
        this.o00000.put("Liturgie: Parinors Verm\u00e4chtnis", "Lit: Parinors Verm\u00e4chtnis");
        this.o00000.put("Liturgie: Peraines Pflanzengesp\u00fcr", "Lit: Peraines Pflanzengesp\u00fcr");
        this.o00000.put("Liturgie: Phexens Augenzwinkern", "Lit: Phexens Augenzwinkern");
        this.o00000.put("Liturgie: Phexens Elsterflug", "Lit: Phexens Elsterflug");
        this.o00000.put("Liturgie: Phexens Kunstverstand", "Lit: Phexens Kunstverstand");
        this.o00000.put("Liturgie: Phexens Meisterschl\u00fcssel", "Lit: Phexens Meisterschl\u00fcssel");
        this.o00000.put("Liturgie: Phexens Nebelleib", "Lit: Phexens Nebelleib");
        this.o00000.put("Liturgie: Phexens Schatten", "Lit: Phexens Schatten");
        this.o00000.put("Liturgie: Phexens Sternenwurf", "Lit: Phexens Sternenwurf");
        this.o00000.put("Liturgie: Phexens wunderbare Verst\u00e4ndigung", "Lit: Phexens Verst\u00e4ndigung");
        this.o00000.put("Liturgie: Praios Mahnung", "Lit: Praios Mahnung");
        this.o00000.put("Liturgie: Praios' Magiebann", "Lit: Praios' Magiebann");
        this.o00000.put("Liturgie: Prophezeiung", "Lit: Prophezeiung");
        this.o00000.put("Liturgie: Purgation", "Lit: Purgation");
        this.o00000.put("Liturgie: Quellsegen", "Lit: Quellsegen");
        this.o00000.put("Liturgie: Rahjalinas Kuss", "Lit: Rahjalinas Kuss");
        this.o00000.put("Liturgie: Rahjalinas Weinranke", "Lit: Rahjalinas Weinranke");
        this.o00000.put("Liturgie: Rahjas Erquickung", "Lit: Rahjas Erquickung");
        this.o00000.put("Liturgie: Rahjas Fest der Freude", "Lit: Rahjas Fest der Freude");
        this.o00000.put("Liturgie: Rahjas Freiheit", "Lit: Rahjas Freiheit");
        this.o00000.put("Liturgie: Rahjas geheiligter Wein", "Lit: Rahjas geheiligter Wein");
        this.o00000.put("Liturgie: Rahjas heitere Gelassenheit", "Lit: Rahjas Gelassenheit");
        this.o00000.put("Liturgie: Rahjas Rauschsegen", "Lit: Rahjas Rauschsegen");
        this.o00000.put("Liturgie: Rahjas Scho\u00df", "Lit: Rahjas Scho\u00df");
        this.o00000.put("Liturgie: Rahjas Sinnlichkeit", "Lit: Rahjas Sinnlichkeit");
        this.o00000.put("Liturgie: Reichung des Amethyst", "Lit: Reichung des Amethyst");
        this.o00000.put("Liturgie: Reisesegen", "Lit: Reisesegen");
        this.o00000.put("Liturgie: Rondras Hochzeit", "Lit: Rondras Hochzeit");
        this.o00000.put("Liturgie: Rondras wundersame R\u00fcstung", "Lit: Rondras R\u00fcstung");
        this.o00000.put("Liturgie: Ruf der Gef\u00e4hrten", "Lit: Ruf der Gef\u00e4hrten");
        this.o00000.put("Liturgie: Ruf in Borons Arme", "Lit: Ruf in Borons Arme");
        this.o00000.put("Liturgie: Ruf zur Ruhe", "Lit: Ruf zur Ruhe");
        this.o00000.put("Liturgie: Salbung der Heiligen Noiona", "Lit: Salbung der Hlg. Noiona");
        this.o00000.put("Liturgie: Sankt Gilborns Bannfluch", "Lit: Sankt Gilborns Bannfluch");
        this.o00000.put("Liturgie: Schattenlarve", "Lit: Schattenlarve");
        this.o00000.put("Liturgie: Schiffssegen", "Lit: Schiffssegen");
        this.o00000.put("Liturgie: Schlaf des Gesegneten", "Lit: Schlaf des Gesegneten");
        this.o00000.put("Liturgie: Schlangenstab", "Lit: Schlangenstab");
        this.o00000.put("Liturgie: Schneesturm/Eissturm", "Lit: Schneesturm/Eissturm");
        this.o00000.put("Liturgie: Schrifttum ferner Lande", "Lit: Schrifttum ferner Lande");
        this.o00000.put("Liturgie: Schutz des Geleges", "Lit: Schutz des Geleges");
        this.o00000.put("Liturgie: Schutzsegen", "Lit: Schutzsegen");
        this.o00000.put("Liturgie: Das Schwarze Fell durch das Rote Blut", "Lit: Schwarzes Fell d. Rotes Blut");
        this.o00000.put("Liturgie: Schwitzh\u00fctte", "Lit: Schwitzh\u00fctte");
        this.o00000.put("Liturgie: Seelenpr\u00fcfung", "Lit: Seelenpr\u00fcfung");
        this.o00000.put("Liturgie: Segnung der St\u00e4hlernen Stirn", "Lit: Seg. der St\u00e4hlernen Stirn");
        this.o00000.put("Liturgie: Segen der Gabetaj", "Lit: Segen der Gabetaj");
        this.o00000.put("Liturgie: Segen der Heiligen Ardare", "Lit: Segen der Hlg. Ardare");
        this.o00000.put("Liturgie: Segen der Heiligen Noiona", "Lit: Segen der Hlg. Noiona");
        this.o00000.put("Liturgie: Segen der Heiligen Theria", "Lit: Segen der Hlg. Theria");
        this.o00000.put("Liturgie: Segen der Heiligen Velvenya", "Lit: Segen der Hlg. Velvenya");
        this.o00000.put("Liturgie: Segen des Heiligen Badilak", "Lit: Segen des Hlg. Badilak");
        this.o00000.put("Liturgie: Segen des Heiligen Hl\u00fbthar", "Lit: Segen des Hlg. Hl\u00fbthar");
        this.o00000.put("Liturgie: Segen des Pl\u00e4ttlings", "Lit: Segen des Pl\u00e4ttlings");
        this.o00000.put("Liturgie: Segnung der Schlacht", "Lit: Segnung der Schlacht");
        this.o00000.put("Liturgie: Segnung des Heimes", "Lit: Segnung des Heimes");
        this.o00000.put("Liturgie: Sichere Wanderung im Schnee", "Lit: Sichere Wanderung");
        this.o00000.put("Liturgie: Sicherer Weg durch Fels", "Lit: Sicherer Weg durch Fels");
        this.o00000.put("Liturgie: Sicht auf Madas Welt", "Lit: Sicht auf Madas Welt");
        this.o00000.put("Liturgie: Siegel Borons", "Lit: Siegel Borons");
        this.o00000.put("Liturgie: Simias Kelch", "Lit: Simias Kelch");
        this.o00000.put("Liturgie: Sippenfluch", "Lit: Sippenfluch");
        this.o00000.put("Liturgie: Speisung der hungernden Seele", "Lit: Speis. d. hungernden Seele");
        this.o00000.put("Liturgie: Speisesegen", "Lit: Speisesegen");
        this.o00000.put("Liturgie: Speisung der Bed\u00fcrftigen", "Lit: Speisung der Bed\u00fcrftigen");
        this.o00000.put("Liturgie: Sprechende Symbole", "Lit: Sprechende Symbole");
        this.o00000.put("Liturgie: Sterne funkeln immerfort", "Lit: Sterne funkeln immerfort");
        this.o00000.put("Liturgie: Sternenglanz", "Lit: Sternenglanz");
        this.o00000.put("Liturgie: Sternenspur", "Lit: Sternenspur");
        this.o00000.put("Liturgie: Sternenstaub", "Lit: Sternenstaub");
        this.o00000.put("Liturgie: Sulvas Gnade", "Lit: Sulvas Gnade");
        this.o00000.put("Liturgie: Swafnirs Fluke", "Lit: Swafnirs Fluke");
        this.o00000.put("Liturgie: Swafnirs Ruhelied", "Lit: Swafnirs Ruhelied");
        this.o00000.put("Liturgie: Tabu", "Lit: Tabu");
        this.o00000.put("Liturgie: Tairachs Fluch", "Lit: Tairachs Fluch");
        this.o00000.put("Liturgie: Thalionmels Schlachtgesang", "Lit: Thalion. Schlachtgesang");
        this.o00000.put("Liturgie: Therb\u00fbns Erkenntnis", "Lit: Therb\u00fbns Erkenntnis");
        this.o00000.put("Liturgie: Tierempathie", "Lit: Tierempathie");
        this.o00000.put("Liturgie: Tiergestalt", "Lit: Tiergestalt");
        this.o00000.put("Liturgie: Tiersprache", "Lit: Tiersprache");
        this.o00000.put("Liturgie: Travias Gebet der sicheren Zuflucht", "Lit: TRA G. d. sicheren Zuflucht");
        this.o00000.put("Liturgie: Travias Gebet der verborgenen Halle", "Lit: TRA G. d. verborg. Halle");
        this.o00000.put("Liturgie: Tranksegen", "Lit: Tranksegen");
        this.o00000.put("Liturgie: Traviabund", "Lit: Traviabund");
        this.o00000.put("Liturgie: Travinians Segen der Schwelle", "Lit: Travinians S. der Schwelle");
        this.o00000.put("Liturgie: Troph\u00e4e erhalten", "Lit: Troph\u00e4e erhalten");
        this.o00000.put("Liturgie: Tsas ewige Jugend", "Lit: Tsas ewige Jugend");
        this.o00000.put("Liturgie: Tsas Heiliges Lebensgeschenk", "Lit: Tsas Hlg. Lebensgeschenk");
        this.o00000.put("Liturgie: Tsas Lebensschutz", "Lit: Tsas Lebensschutz");
        this.o00000.put("Liturgie: Tsas Segensreicher Neuanfang", "Lit: Tsas Segensr. Neuanfang");
        this.o00000.put("Liturgie: Tsas Wunderbare Erneuerung", "Lit: Tsas Wun. Erneuerung");
        this.o00000.put("Liturgie: Tsas Wundersame Fruchtbarkeit", "Lit: Tsas Wun. Fruchtbarkeit");
        this.o00000.put("Liturgie: \u00dcber die Wolken", "Lit: \u00dcber die Wolken");
        this.o00000.put("Liturgie: Ucuris Geleit", "Lit: Ucuris Geleit");
        this.o00000.put("Liturgie: Unterpfand des Heiligen Rhys", "Lit: Unterpfand des Hlg. Rhys");
        this.o00000.put("Liturgie: Unverstellter Blick", "Lit: Unverstellter Blick");
        this.o00000.put("Liturgie: Urischars ordnender Blick", "Lit: Urischars ordnender Blick");
        this.o00000.put("Liturgie: Va\u00eas Tr\u00e4nen", "Lit: Va\u00eas Tr\u00e4nen");
        this.o00000.put("Liturgie: Verborgen wie der Neumond", "Lit: Verborgen w. d. Neumond");
        this.o00000.put("Liturgie: Versiegeltes Wissen", "Lit: Versiegeltes Wissen");
        this.o00000.put("Liturgie: Vertrauter der Flamme", "Lit: Vertrauter der Flamme");
        this.o00000.put("Liturgie: Vertrauter des Felsens", "Lit: Vertrauter des Felsens");
        this.o00000.put("Liturgie: Vertreibung des Dunkelsinns", "Lit: Vertreibung d. Dunkelsinns");
        this.o00000.put("Liturgie: Visionssuche", "Lit: Visionssuche");
        this.o00000.put("Liturgie: Waliburias Wehr", "Lit: Waliburias Wehr");
        this.o00000.put("Liturgie: Wandeln in Hesindes Hain", "Lit: Wandeln in Hesindes Hain");
        this.o00000.put("Liturgie: Weg des Fuchses", "Lit: Weg des Fuchses");
        this.o00000.put("Liturgie: Weihe der letzten Ruhestatt", "Lit: Weihe d. letzten Ruhestatt");
        this.o00000.put("Liturgie: Weihe der Ewigen Flamme", "Lit: Weihe der Ewigen Flamme");
        this.o00000.put("Liturgie: Weihegesang der Heiligen Elida von Salza", "Lit: Weihegesang d. Hlg. Elida");
        this.o00000.put("Liturgie: Weisheitssegen", "Lit: Weisheitssegen");
        this.o00000.put("Liturgie: Weisung des Himmels", "Lit: Weisung des Himmels");
        this.o00000.put("Liturgie: Wille zur Wahrheit", "Lit: Wille zur Wahrheit");
        this.o00000.put("Liturgie: Winterschlaf", "Lit: Winterschlaf");
        this.o00000.put("Liturgie: Wort der Wahrheit", "Lit: Wort der Wahrheit");
        this.o00000.put("Liturgie: Wunderbarer Geschlechterwandel", "Lit: Wund. Geschlechterwandel");
        this.o00000.put("Liturgie: Wundersame Bl\u00fctenpracht", "Lit: Wundersame Bl\u00fctenpracht");
        this.o00000.put("Liturgie: Wundsegen", "Lit: Wundsegen");
        this.o00000.put("Liturgie: Zerschmetternder Bannstrahl", "Lit: Zerschmett. Bannstrahl");
        this.o00000.put("Liturgie: Zuflucht finden", "Lit: Zuflucht finden");
        this.o00000.put("Liturgiekenntnis (Angrosch)", "LK (Angrosch)");
        this.o00000.put("Liturgiekenntnis (Aves)", "LK (Aves)");
        this.o00000.put("Liturgiekenntnis (Boron)", "LK (Boron)");
        this.o00000.put("Liturgiekenntnis (Efferd)", "LK (Efferd)");
        this.o00000.put("Liturgiekenntnis (Firun)", "LK (Firun)");
        this.o00000.put("Liturgiekenntnis (Gravesh)", "LK (Gravesh)");
        this.o00000.put("Liturgiekenntnis (H'Ranga)", "LK (H'Ranga)");
        this.o00000.put("Liturgiekenntnis (H'Szint)", "LK (H'Szint)");
        this.o00000.put("Liturgiekenntnis (Hesinde)", "LK (Hesinde)");
        this.o00000.put("Liturgiekenntnis (Ifirn)", "LK (Ifirn)");
        this.o00000.put("Liturgiekenntnis (Ingerimm)", "LK (Ingerimm)");
        this.o00000.put("Liturgiekenntnis (Kamaluq)", "LK (Kamaluq)");
        this.o00000.put("Liturgiekenntnis (Kor)", "LK (Kor)");
        this.o00000.put("Liturgiekenntnis (Nandus)", "LK (Nandus)");
        this.o00000.put("Liturgiekenntnis (Peraine)", "LK (Peraine)");
        this.o00000.put("Liturgiekenntnis (Phex)", "LK (Phex)");
        this.o00000.put("Liturgiekenntnis (Praios)", "LK (Praios)");
        this.o00000.put("Liturgiekenntnis (Rahja)", "LK (Rahja)");
        this.o00000.put("Liturgiekenntnis (Rondra)", "LK (Rondra)");
        this.o00000.put("Liturgiekenntnis (Swafnir)", "LK (Swafnir)");
        this.o00000.put("Liturgiekenntnis (Tairach)", "LK (Tairach)");
        this.o00000.put("Liturgiekenntnis (Travia)", "LK (Travia)");
        this.o00000.put("Liturgiekenntnis (Tsa)", "LK (Tsa)");
        this.o00000.put("Liturgiekenntnis (Zsahh)", "LK (Zsahh)");
        this.o00000.put("Merkmalskenntnis: Antimagie", "MK: Antimagie");
        this.o00000.put("Merkmalskenntnis: Beschw\u00f6rung", "MK: Beschw\u00f6rung");
        this.o00000.put("Merkmalskenntnis: D\u00e4monisch (Agrimoth)", "MK: D\u00e4m. (Agrimoth)");
        this.o00000.put("Merkmalskenntnis: D\u00e4monisch (Amazeroth)", "MK: D\u00e4m. (Amazeroth)");
        this.o00000.put("Merkmalskenntnis: D\u00e4monisch (Asfaloth)", "MK: D\u00e4m. (Asfaloth)");
        this.o00000.put("Merkmalskenntnis: D\u00e4monisch (Belhalhar)", "MK: D\u00e4m. (Belhalhar)");
        this.o00000.put("Merkmalskenntnis: D\u00e4monisch (Belzhorash)", "MK: D\u00e4m. (Belzhorash)");
        this.o00000.put("Merkmalskenntnis: D\u00e4monisch (Blakharaz)", "MK: D\u00e4m. (Blakharaz)");
        this.o00000.put("Merkmalskenntnis: D\u00e4monisch (Lolgramoth)", "MK: D\u00e4m. (Lolgramoth)");
        this.o00000.put("Merkmalskenntnis: D\u00e4monisch (Mishkara)", "MK: D\u00e4m. (Mishkara)");
        this.o00000.put("Merkmalskenntnis: D\u00e4monisch (Targunitoth)", "MK: D\u00e4m. (Targunitoth)");
        this.o00000.put("Merkmalskenntnis: D\u00e4monisch", "MK: D\u00e4monisch");
        this.o00000.put("Merkmalskenntnis: Eigenschaften", "MK: Eigenschaften");
        this.o00000.put("Merkmalskenntnis: Einfluss", "MK: Einfluss");
        this.o00000.put("Merkmalskenntnis: Elementar", "MK: Elementar");
        this.o00000.put("Merkmalskenntnis: Elementar (Eis)", "MK: Elementar (Eis)");
        this.o00000.put("Merkmalskenntnis: Elementar (Erz)", "MK: Elementar (Erz)");
        this.o00000.put("Merkmalskenntnis: Elementar (Feuer)", "MK: Elementar (Feuer)");
        this.o00000.put("Merkmalskenntnis: Elementar (Humus)", "MK: Elementar (Humus)");
        this.o00000.put("Merkmalskenntnis: Elementar (Luft)", "MK: Elementar (Luft)");
        this.o00000.put("Merkmalskenntnis: Elementar (Wasser)", "MK: Elementar (Wasser)");
        this.o00000.put("Merkmalskenntnis: Form", "MK: Form");
        this.o00000.put("Merkmalskenntnis: Geisterwesen", "MK: Geisterwesen");
        this.o00000.put("Merkmalskenntnis: Heilung", "MK: Heilung");
        this.o00000.put("Merkmalskenntnis: Hellsicht", "MK: Hellsicht");
        this.o00000.put("Merkmalskenntnis: Herbeirufung", "MK: Herbeirufung");
        this.o00000.put("Merkmalskenntnis: Herrschaft", "MK: Herrschaft");
        this.o00000.put("Merkmalskenntnis: Illusion", "MK: Illusion");
        this.o00000.put("Merkmalskenntnis: Kraft", "MK: Kraft");
        this.o00000.put("Merkmalskenntnis: Limbus", "MK: Limbus");
        this.o00000.put("Merkmalskenntnis: Metamagie", "MK: Metamagie");
        this.o00000.put("Merkmalskenntnis: Objekt", "MK: Objekt");
        this.o00000.put("Merkmalskenntnis: Schaden", "MK: Schaden");
        this.o00000.put("Merkmalskenntnis: Telekinese", "MK: Telekinese");
        this.o00000.put("Merkmalskenntnis: Temporal", "MK: Temporal");
        this.o00000.put("Merkmalskenntnis: Umwelt", "MK: Umwelt");
        this.o00000.put("Merkmalskenntnis: Verst\u00e4ndigung", "MK: Verst\u00e4ndigung");
    }

    private void \u00d200000() {
        this.o00000.put("Ritual: Arngrims H\u00f6hle", "Rit:Arngrims H\u00f6hle");
        this.o00000.put("Ritual: Aufmerksamer W\u00e4chter", "Rit:Aufmerksamer W\u00e4chter");
        this.o00000.put("Ritual: Blick in Liskas Augen", "Rit:Blick in Liskas Augen");
        this.o00000.put("Ritual: Blick ins Geisterreich", "Rit:Blick ins Geisterreich");
        this.o00000.put("Ritual: Blutsbund", "Rit:Blutsbund");
        this.o00000.put("Ritual: Brazoragh Ghorkai", "Rit:Brazoragh Ghorkai");
        this.o00000.put("Ritual: Ergochai Tairachi", "Rit:Ergochai Tairachi");
        this.o00000.put("Ritual: Exorzismus", "Rit:Exorzismus");
        this.o00000.put("Ritual: Farben des Krieges", "Rit:Farben des Krieges");
        this.o00000.put("Ritual: Fluch der Verwirrung", "Rit:Fluch der Verwirrung");
        this.o00000.put("Ritual: Freie Seelenfahrt", "Rit:Freie Seelenfahrt");
        this.o00000.put("Ritual: Gaben der Erde", "Rit:Gaben der Erde");
        this.o00000.put("Ritual: Geisterbote", "Rit:Geisterbote");
        this.o00000.put("Ritual: Geisterkerker", "Rit:Geisterkerker");
        this.o00000.put("Ritual: Geistheilung", "Rit:Geistheilung");
        this.o00000.put("Ritual: Geleit des Nipakau", "Rit:Geleit des Nipakau");
        this.o00000.put("Ritual: Gesang der W\u00f6lfe", "Rit:Gesang der W\u00f6lfe");
        this.o00000.put("Ritual: Gharyak Maruki", "Rit:Gharyak Maruki");
        this.o00000.put("Ritual: Hairuf", "Rit:Hairuf");
        this.o00000.put("Ritual: Hauch der Luft", "Rit:Hauch der Luft");
        this.o00000.put("Ritual: Hauch des Eises", "Rit:Hauch des Eises");
        this.o00000.put("Ritual: Hauch des Erzes", "Rit:Hauch des Erzes");
        this.o00000.put("Ritual: Hauch des Feuers", "Rit:Hauch des Feuers");
        this.o00000.put("Ritual: Hauch des Humus", "Rit:Hauch des Humus");
        this.o00000.put("Ritual: Hauch des Wassers", "Rit:Hauch des Wassers");
        this.o00000.put("Ritual: Heimf\u00fchrung der Herde", "Rit:Heimf\u00fchrung der Herde");
        this.o00000.put("Ritual: Herz des Tieres", "Rit:Herz des Tieres");
        this.o00000.put("Ritual: Hilferuf", "Rit:Hilferuf");
        this.o00000.put("Ritual: Jagdfieber", "Rit:Jagdfieber");
        this.o00000.put("Ritual: Khurkachai Tairachi", "Rit:Khurkachai Tairachi");
        this.o00000.put("Ritual: Kraft der Tayas", "Rit:Kraft der Tayas");
        this.o00000.put("Ritual: Kraft des Tieres", "Rit:Kraft des Tieres");
        this.o00000.put("Ritual: M\u00b4char Utrak Rikaii", "Rit:M\u00b4char Utrak Rikaii");
        this.o00000.put("Ritual: Macht der Elemente", "Rit:Macht der Elemente");
        this.o00000.put("Ritual: Macht des Blutes", "Rit:Macht des Blutes");
        this.o00000.put("Ritual: Mailam Rekdais Segen", "Rit:Mailam Rekdais Segen");
        this.o00000.put("Ritual: Mammutruf", "Rit:Mammutruf");
        this.o00000.put("Ritual: Ogerruf", "Rit:Ogerruf");
        this.o00000.put("Ritual: Pfad der Blutrache", "Rit:Pfad der Blutrache");
        this.o00000.put("Ritual: Rat der Ahnen", "Rit:Rat der Ahnen");
        this.o00000.put("Ritual: Regentanz", "Rit:Regentanz");
        this.o00000.put("Ritual: Reinigen des Wassers", "Rit:Reinigen des Wassers");
        this.o00000.put("Ritual: Rei\u00dfgrams F\u00e4hrte", "Rit:Rei\u00dfgrams F\u00e4hrte");
        this.o00000.put("Ritual: Reitender Geist", "Rit:Reitender Geist");
        this.o00000.put("Ritual: Rikais Verderben", "Rit:Rikais Verderben");
        this.o00000.put("Ritual: Rinderruf", "Rit:Rinderruf");
        this.o00000.put("Ritual: Ruf des Schamanen", "Rit:Ruf des Schamanen");
        this.o00000.put("Ritual: Schlangenfluch", "Rit:Schlangenfluch");
        this.o00000.put("Ritual: Schlangengeist", "Rit:Schlangengeist");
        this.o00000.put("Ritual: Schlingerruf", "Rit:Schlingerruf");
        this.o00000.put("Ritual: Schomas Kraft", "Rit:Schomas Kraft");
        this.o00000.put("Ritual: Schutz der Jurte", "Rit:Schutz der Jurte");
        this.o00000.put("Ritual: Sch\u00fctzende Rotte", "Rit:Sch\u00fctzende Rotte");
        this.o00000.put("Ritual: Seeschlangenruf", "Rit:Seeschlangenruf");
        this.o00000.put("Ritual: Stimme des Nipakau", "Rit:Stimme des Nipakau");
        this.o00000.put("Ritual: Tabuzone", "Rit:Tabuzone");
        this.o00000.put("Ritual: Tauschplatz", "Rit:Tauschplatz");
        this.o00000.put("Ritual: Tiere aus Farben", "Rit:Tiere aus Farben");
        this.o00000.put("Ritual: Tr\u00e4nke meine Herde", "Rit:Tr\u00e4nke meine Herde");
        this.o00000.put("Ritual: Weckruf", "Rit:Weckruf");
        this.o00000.put("Ritual: Weg des Windes", "Rit:Weg des Windes");
        this.o00000.put("Ritual: Weidegr\u00fcnde finden", "Rit:Weidegr\u00fcnde finden");
        this.o00000.put("Ritual: Wild finden", "Rit:Wild finden");
        this.o00000.put("Ritual: Wildschweinruf", "Rit:Wildschweinruf");
        this.o00000.put("Ritual: Wolfsfluch", "Rit:Wolfsfluch");
        this.o00000.put("Ritual: Wolfsruf", "Rit:Wolfsruf");
        this.o00000.put("Ritual: Zeichen setzen", "Rit:Zeichen setzen");
        this.o00000.put("Ritual: Zorn des Bergl\u00f6wen", "Rit:Zorn des Bergl\u00f6wen");
        this.o00000.put("Repr\u00e4sentation: Achaz", "Rep: Achaz");
        this.o00000.put("Repr\u00e4sentation: Borbaradianer", "Rep: Borbaradianer");
        this.o00000.put("Repr\u00e4sentation: Druide", "Rep: Druide");
        this.o00000.put("Repr\u00e4sentation: Elf", "Rep: Elf");
        this.o00000.put("Repr\u00e4sentation: Geode", "Rep: Geode");
        this.o00000.put("Repr\u00e4sentation: Hexe", "Rep: Hexe");
        this.o00000.put("Repr\u00e4sentation: Magier", "Rep: Magier");
        this.o00000.put("Repr\u00e4sentation: Scharlatan", "Rep: Scharlatan");
        this.o00000.put("Repr\u00e4sentation: Schelm", "Rep: Schelm");
        this.o00000.put("Ritualkenntnis: Achaz-Schamane", "RK: Achaz-Schamane");
        this.o00000.put("Ritualkenntnis: Alchimist", "RK: Alchimist");
        this.o00000.put("Ritualkenntnis: Derwisch", "RK: Derwisch");
        this.o00000.put("Ritualkenntnis: Druide", "RK: Druide");
        this.o00000.put("Ritualkenntnis: Durro-D\u00fbn", "RK: Durro-D\u00fbn");
        this.o00000.put("Ritualkenntnis: Ferkina-Schamane", "RK: Ferkina-Schamane");
        this.o00000.put("Ritualkenntnis: Geode", "RK: Geode");
        this.o00000.put("Ritualkenntnis: Gildenmagie", "RK: Gildenmagie");
        this.o00000.put("Ritualkenntnis: Gjalsker-Schamane", "RK: Gjalsker-Schamane");
        this.o00000.put("Ritualkenntnis: Goblin-Schamanin", "RK: Goblin-Schamanin");
        this.o00000.put("Ritualkenntnis: Hexe", "RK: Hexe");
        this.o00000.put("Ritualkenntnis: Kristallomantie", "RK: Kristallomantie");
        this.o00000.put("Ritualkenntnis: Nivesen-Schamane", "RK: Nivesen-Schamane");
        this.o00000.put("Ritualkenntnis: Ork-Schamane", "RK: Ork-Schamane");
        this.o00000.put("Ritualkenntnis: Scharlatan", "RK: Scharlatan");
        this.o00000.put("Ritualkenntnis: Trollzacker-Schamane", "RK: Trollzacker-Schamane");
        this.o00000.put("Ritualkenntnis: Waldmenschen-Schamane", "RK: Waldmensch-Schamane");
        this.o00000.put("Ritualkenntnis: Zaubert\u00e4nzer", "RK: Zaubert\u00e4nzer");
        this.o00000.put("Ritualkenntnis: Zibilja", "RK: Zibilja");
        this.o00000.put("Schuppenbeutel: Bindung des Schuppenbeutels", "SB: Bindung des Beutels");
        this.o00000.put("Schuppenbeutel: Ewige Wegzehrung", "SB: Ewige Wegzehrung");
        this.o00000.put("Schuppenbeutel: Suchende Finger", "SB: Suchende Finger");
        this.o00000.put("Schalenzauber: Allegorische Analyse", "SchZ: Allegorische Analyse");
        this.o00000.put("Schalenzauber: Chymische Hochzeit", "SchZ: Chymische Hochzeit");
        this.o00000.put("Schalenzauber: Feuer und Eis", "SchZ: Feuer und Eis");
        this.o00000.put("Schalenzauber: Mandricons Bindung", "SchZ: Mandricons Bindung");
        this.o00000.put("Schalenzauber: Transmutation der Elemente", "SchZ: Transmut. D. Elemente");
        this.o00000.put("Schalenzauber: Weihe der Schale", "SchZ: Weihe der Schale");
        this.o00000.put("Sp\u00e4tweihe Alveranische Gottheit", "Sp\u00e4tweihe (AG)");
        this.o00000.put("Sp\u00e4tweihe Nichtalveranische Gottheit", "Sp\u00e4tweihe (NAG)");
        this.o00000.put("Schlangenring-Zauber: Herr der Flammen", "SRZ: Herr der Flammen");
        this.o00000.put("Schlangenring-Zauber: Kr\u00e4fte der Natur", "SRZ: Kr\u00e4fte der Natur");
        this.o00000.put("Schlangenring-Zauber: Launen des Windes", "SRZ: Launen des Windes");
        this.o00000.put("Schlangenring-Zauber: Macht des Lebens", "SRZ: Macht des Lebens");
        this.o00000.put("Schlangenring-Zauber: Macht \u00fcber den Regen", "SRZ: Macht \u00fcber den Regen");
        this.o00000.put("Schlangenring-Zauber: Magnetismus", "SRZ: Magnetismus");
        this.o00000.put("Schlangenring-Zauber: Seelenfeuer", "SRZ: Seelenfeuer");
        this.o00000.put("Schlangenring-Zauber: Wasserbann", "SRZ: Wasserbann");
        this.o00000.put("Schlangenring-Zauber: Weg durch Sumus Leib", "SRZ: Weg durch Sumus Leib");
        this.o00000.put("Schlangenring-Zauber: Weihe der Schlange", "SRZ: Weihe der Schlange");
        this.o00000.put("Schlangenring-Zauber: Wirbelnder Luftschild", "SRZ: Wirbelnder Luftschild");
        this.o00000.put("Stabzauber: Bindung", "StZ: Bindung");
        this.o00000.put("Stabzauber: Fackel", "StZ: Fackel");
        this.o00000.put("Stabzauber: Flammenschwert", "StZ: Flammenschwert");
        this.o00000.put("Stabzauber: Hammer das Magus", "StZ: Hammer das Magus");
        this.o00000.put("Stabzauber: Kraftfokus", "StZ: Kraftfokus");
        this.o00000.put("Stabzauber: Merkmalsfokus", "StZ: Merkmalsfokus");
        this.o00000.put("Stabzauber: Modifikationsfokus", "StZ: Modifikationsfokus");
        this.o00000.put("Stabzauber: Schuppenhaut", "StZ: Schuppenhaut");
        this.o00000.put("Stabzauber: Seil", "StZ: Seil");
        this.o00000.put("Stabzauber: Stabverl\u00e4ngerung", "StZ: Stabverl\u00e4ngerung");
        this.o00000.put("Stabzauber: Zauberspeicher", "StZ: Zauberspeicher");
        this.o00000.put("Trommelzauber: Rastullahs G\u00fcte", "TZ: Rastullahs G\u00fcte");
        this.o00000.put("Trommelzauber: Ruf des Krieges", "TZ: Ruf des Krieges");
        this.o00000.put("Trommelzauber: Schutz Rastullahs", "TZ: Schutz Rastullahs");
        this.o00000.put("Trommelzauber: Sturm der W\u00fcste", "TZ: Sturm der W\u00fcste");
        this.o00000.put("Trommelzauber: Zorn des Gottgef\u00e4lligen", "TZ: Zorn des Gottgef\u00e4lligen");
        this.o00000.put("Waffenloser Kampfstil: Bornl\u00e4ndisch", "Wl. KS: Bornl\u00e4ndisch");
        this.o00000.put("Waffenloser Kampfstil: Gladiatorenstil", "Wl. KS: Gladiatorenstil");
        this.o00000.put("Waffenloser Kampfstil: Hammerfaust", "Wl. KS: Hammerfaust");
        this.o00000.put("Waffenloser Kampfstil: Hruruzat", "Wl. KS: Hruruzat");
        this.o00000.put("Waffenloser Kampfstil: Mercenario", "Wl. KS: Mercenario");
        this.o00000.put("Waffenloser Kampfstil: Unauer Schule", "Wl. KS: Unauer Schule");
        this.o00000.put("Zibilja-Ritual: Bienenflei\u00df", "Zibilja-R: Bienenflei\u00df");
        this.o00000.put("Zibilja-Ritual: Bienenk\u00f6nigin", "Zibilja-R: Bienenk\u00f6nigin");
        this.o00000.put("Zibilja-Ritual: Bienenschwarm", "Zibilja-R: Bienenschwarm");
        this.o00000.put("Zibilja-Ritual: Bienentanz", "Zibilja-R: Bienentanz");
        this.o00000.put("Zibilja-Ritual: Mackestopp", "Zibilja-R: Mackestopp");
        this.o00000.put("Zibilja-Ritual: Ruf des Bienenstocks", "Zibilja-R: Ruf d. Bienenstocks");
        this.o00000.put("Zibilja-Ritual: Schwarmseele", "Zibilja-R: Schwarmseele");
        this.o00000.put("Zibilja-Ritual: Siegel der Ewigen Ruhe", "Zibilja-R: Siegel d. Ew. Ruhe");
        this.o00000.put("Zibilja-Ritual: Traumseherin", "Zibilja-R: Traumseherin");
        this.o00000.put("Zibilja-Ritual: Traumwissen", "Zibilja-R: Traumwissen");
        this.o00000.put("Zibilja-Ritual: Unsichtbare Chronik", "Zibilja-R: Unsichtb. Chronik");
        this.o00000.put("Zibilja-Ritual: Wachshaut", "Zibilja-R: Wachshaut");
        this.o00000.put("Zibilja-Ritual: Weisheit der Schrift", "Zibilja-R: Weisheit d. Schrift");
        this.o00000.put("Zibilja-Ritual: Winterlager", "Zibilja-R: Winterlager");
        this.o00000.put("Zaubertanz: Firuns Jagd", "ZT: Firuns Jagd");
        this.o00000.put("Zaubertanz: Madayana", "ZT: Madayana");
        this.o00000.put("Zaubertanz: Rahjas Begehren", "ZT: Rahjas Begehren");
        this.o00000.put("Zaubertanz: Selinata", "ZT: Selinata");
        this.o00000.put("Zaubertanz: Tanz der Unantastbarkeit", "ZT: Tanz d. Unantastbarkeit");
        this.o00000.put("Zaubertanz: Tanz der Bilder", "ZT: Tanz der Bilder");
        this.o00000.put("Zaubertanz: Tanz der Erl\u00f6sung", "ZT: Tanz der Erl\u00f6sung");
        this.o00000.put("Zaubertanz: Tanz der Ermutigung", "ZT: Tanz der Ermutigung");
        this.o00000.put("Zaubertanz: Tanz der Freude", "ZT: Tanz der Freude");
        this.o00000.put("Zaubertanz: Tanz der Gemeinschaft", "ZT: Tanz der Gemeinschaft");
        this.o00000.put("Zaubertanz: Tanz der Liebe", "ZT: Tanz der Liebe");
        this.o00000.put("Zaubertanz: Tanz der Wahrheit", "ZT: Tanz der Wahrheit");
        this.o00000.put("Zaubertanz: Tanz der Weisheit", "ZT: Tanz der Weisheit");
        this.o00000.put("Zaubertanz: Tanz des Ungehorsams", "ZT: Tanz des Ungehorsams");
        this.o00000.put("Zaubertanz: Tanz ohne Ende", "ZT: Tanz ohne Ende");
        this.o00000.put("Zauberzeichen: Bann- und Schutzkreis gegen Elementare", "Kreis geg. Elementare");
        this.o00000.put("Zauberzeichen: Bann- und Schutzkreis gegen geh\u00f6rnte D\u00e4monen", "Kreis geg. geh. D\u00e4m.");
        this.o00000.put("Zauberzeichen: Bann- und Schutzkreis gegen Geisterwesen", "Kreis geg. Geisterwesen");
        this.o00000.put("Zauberzeichen: Bann- und Schutzkreis gegen niedere D\u00e4monen", "Kreis geg. niedere D\u00e4m.");
        this.o00000.put("Zauberzeichen: Bann- und Schutzkreis gegen Reptilien", "Kreis geg. Reptilien");
        this.o00000.put("Zauberzeichen: Bann- und Schutzkreis gegen Ungeziefer", "Kreis geg. Ungeziefer");
    }
}

