/*
 * Decompiled with CFR 0.152.
 */
package helden.framework.held;

import helden.framework.C.I;
import helden.framework.C.J;
import helden.framework.C.M;
import helden.framework.D.P;
import helden.framework.DruckEinstellungen;
import helden.framework.E.C.void;
import helden.framework.E.OoOO.A;
import helden.framework.E.OoOO.F;
import helden.framework.E.if;
import helden.framework.Einstellungen;
import helden.framework.OOoO.R;
import helden.framework.OoOO.E;
import helden.framework.OoOO.U;
import helden.framework.OoOO.voidsuper;
import helden.framework.d.oooo.a_0;
import helden.framework.d.oooo.oooo_4;
import helden.framework.e.oooo.oooo_0;
import helden.framework.held.B;
import helden.framework.held.D;
import helden.framework.held.OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO;
import helden.framework.held.while;
import helden.framework.oooo.b_0;
import helden.framework.oooo.oo0o_0;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Set;

/*
 * Illegal identifiers - consider using --renameillegalidents true
 */
public class oO0O {
    private helden.framework.E.F[] public = new helden.framework.E.F[5];
    private helden.framework.E.F[] OO0000 = new helden.framework.E.F[3];
    private helden.framework.E.F[] \u00f5o0000 = new helden.framework.E.F[2];
    private ArrayList<helden.framework.E.F> \u00d5o0000 = new ArrayList();
    private Integer[] \u00d6o0000 = new Integer[5];
    private Integer[] \u00f600000 = new Integer[5];
    private helden.framework.e.oooo_0[] \u00d5O0000;
    private if[] O\u00d20000;
    private helden.framework.E.C.B intsuper;
    private int[] \u00d2O0000 = new int[]{0, 0, 0};
    private int[] interfacesuper;
    private int[] \u00d200000;
    private int[] \u00d4o0000 = new int[]{0, 0, 0, 0, 0};
    private int[] \u00d2\u00d20000 = new int[]{0, 0, 0, 0, 0};
    private int o00000;
    private int[] supersuper;
    private int[] \u00f4o0000;
    private F \u00f500000;
    private F \u00d500000;
    private int o\u00d20000;
    private String[] \u00d600000;
    private boolean float;
    private int \u00d2o0000;
    private int \u00f6o0000;
    private int Object;
    private boolean Oo0000;
    private boolean classsuper;
    private boolean \u00f6O0000;
    private boolean oo0000;
    private int[] \u00d400000 = new int[]{0, 0, 0, 0, 0};
    private boolean \u00d6O0000;
    private boolean void;
    private boolean \u00f5O0000;
    private String[] \u00f4O0000;
    private F[] \u00f400000;
    private oooo_0[] \u00d4O0000;
    private while dosuper;
    private int[] oO0000 = new int[]{0, 0, 0, 0, 0};

    public oO0O() {
        this.interfacesuper = new int[]{0, 0};
        this.\u00d200000 = new int[]{0, 0};
        this.supersuper = new int[]{0, 0};
        this.\u00f4o0000 = new int[]{0, 0};
        this.\u00f4O0000 = new String[]{"rechts", "rechts", "rechts", "rechts", "rechts"};
        this.\u00d5O0000 = new helden.framework.e.oooo_0[5];
        this.O\u00d20000 = new if[3];
        this.\u00d600000 = new String[2];
        this.\u00d600000[0] = helden.framework.E.B.super(helden.framework.E.B.\u00d300000);
        this.\u00d600000[1] = helden.framework.E.B.super(helden.framework.E.B.\u00d300000);
        this.\u00f400000 = new F[3];
        this.\u00d4O0000 = new oooo_0[3];
        this.o00000 = 0;
        this.o\u00d20000 = 0;
        this.float = false;
        this.\u00d2o0000 = 0;
        this.\u00f6o0000 = 0;
        this.void = false;
        this.\u00f5O0000 = false;
    }

    public void String(OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2) {
        this.float = Einstellungen.getInstance().getSeitenEinstellungen(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f4o0000()).isZonenRuestung();
        this.o00000(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2, this.float);
    }

    public void o00000(OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2, boolean bl) {
        voidsuper voidsuper2;
        this.\u00d300000(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2);
        this.\u00d200000(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2, bl);
        this.\u00d800000(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2);
        this.\u00d200000(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2);
        this.\u00d600000(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2);
        this.\u00f500000(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2);
        this.\u00d500000(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2);
        this.o00000(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2);
        this.null(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2);
        int n = 0;
        int n2 = 0;
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.iffloatObject.toString())) {
            n2 += 3;
            if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.\u00d2\u00d6\u00d6000.toString())) {
                n2 += 3;
                if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.returnfloatObject.toString())) {
                    n2 += 3;
                }
            }
        }
        n = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d3\u00d30000().\u00f400000();
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f5O0000().\u00d200000(helden.framework.D.while.\u00f50o000.toString()) && this.intsuper != null && this.intsuper.\u00f600000() < 5) {
            n += 4;
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f5O0000().\u00d200000(helden.framework.D.while.\u00f50o000.toString()) && oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f5O0000().\u00d200000(helden.framework.D.while.thisforString.toString()) && this.intsuper != null && this.intsuper.\u00f600000() < 5) {
            n += 2;
        }
        if (this.oo0000 && this.intsuper.\u00f600000() > 3) {
            this.oo0000 = false;
        }
        try {
            if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f5O0000().\u00d200000(helden.framework.D.while.\u00d3\u00d8\u00f6000.toString()) && oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f8O0000().\u00d300000(voidsuper.\u00d4\u00d8\u00d6000) && oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d300000(voidsuper.\u00d4\u00d8\u00d6000) >= 12) {
                int n3 = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d300000(voidsuper.\u00d4\u00d8\u00d6000) - 12;
                n += n3 / 3 + 1;
            }
        }
        catch (D d2) {
            // empty catch block
        }
        this.\u00f6o0000 = n;
        this.\u00d2o0000 = 0;
        this.Object = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.O\u00f4\u00d2000);
        try {
            if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f8O0000().\u00d300000(voidsuper.o\u00d2\u00d8000) && oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d300000(voidsuper.o\u00d2\u00d8000) > 9) {
                this.\u00d2o0000 = (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d300000(voidsuper.o\u00d2\u00d8000) - 9) / 3;
            }
        }
        catch (D d3) {
            // empty catch block
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(I.forpublic)) {
            J j2 = (J)oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d500000().\u00d300000(I.forpublic);
            int n4 = j2.ObjectString();
            if (this.\u00d300000() > 4 && n4 == 1) {
                n4 = 0;
            } else if (this.\u00d300000() > 4 && n4 == 2) {
                n4 = 1;
            } else if (this.\u00d300000() > 6 && n4 == 2) {
                n4 = 0;
            }
            this.\u00d2o0000 += j2.ObjectString();
            this.Object += n4;
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(I.\u00d800000)) {
            M m = (M)oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d500000().\u00d300000(I.\u00d800000);
            for (String object : m.intsuper()) {
                if (!object.startsWith("Beinpaar")) continue;
                this.Object += 3;
            }
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(I.\u00f5\u00f8O000)) {
            --this.\u00d2o0000;
        }
        this.o00000 = this.\u00d2o0000 + n2 - this.\u00d300000() + oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.ifwhilesuper);
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(I.Ooo000)) {
            this.Object -= 3;
            if (this.Object < 1) {
                this.Object = 1;
            }
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d500000().\u00d400000(I.\u00f50\u00d2000)) {
            int n5 = (this.intsuper.\u00f600000() + 1) / 2;
            this.Object -= n5;
            ++this.\u00d2o0000;
            ++this.o00000;
        } else {
            this.Object -= this.intsuper.\u00f600000();
        }
        if (this.Object < 0) {
            this.Object = 0;
        }
        try {
            if (!oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.Oo0000().contains(E.newnewString) && oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d300000(E.newnewString) >= 0) {
                int n6 = this.intsuper.\u00f600000() + E.newnewString.\u00d2\u00d80000();
                if (n6 < 0) {
                    n6 = 0;
                }
                this.interfacesuper[0] = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(E.newnewString) - n6 / 2;
                this.interfacesuper[1] = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(E.newnewString) - (n6 + 1) / 2;
                for (P p2 : oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d5\u00d20000().keySet()) {
                    voidsuper2 = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d5\u00d20000().get(p2);
                    if (voidsuper2 == null || !voidsuper2.toString().equals(E.newnewString.toString())) continue;
                    this.interfacesuper[0] = this.interfacesuper[0] + 1;
                    this.interfacesuper[1] = this.interfacesuper[1] + 1;
                }
                this.\u00f500000 = new F(1, 6, 0).o00000(new A(10, 3).o00000(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.privatedosuper)));
            } else {
                this.\u00f500000 = new F(0, 0, 0);
                this.interfacesuper[0] = 0;
                this.interfacesuper[1] = 0;
            }
        }
        catch (D d4) {
            // empty catch block
        }
        try {
            if (!oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.Oo0000().contains(E.\u00f4\u00d6\u00d8000) && oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d300000(E.\u00f4\u00d6\u00d8000) >= 0) {
                int n7 = this.intsuper.\u00f600000() + E.\u00f4\u00d6\u00d8000.\u00d2\u00d80000();
                if (n7 < 0) {
                    n7 = 0;
                }
                this.\u00d200000[0] = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(E.\u00f4\u00d6\u00d8000) - n7 / 2;
                this.\u00d200000[1] = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(E.\u00f4\u00d6\u00d8000) - (n7 + 1) / 2;
                for (P p3 : oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d5\u00d20000().keySet()) {
                    voidsuper2 = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d5\u00d20000().get(p3);
                    if (voidsuper2 == null || !voidsuper2.toString().equals(E.\u00f4\u00d6\u00d8000.toString())) continue;
                    this.\u00d200000[0] = this.\u00d200000[0] + 1;
                    this.\u00d200000[1] = this.\u00d200000[1] + 1;
                }
                this.\u00d500000 = new F(1, 6, 0).o00000(new A(10, 3).o00000(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.privatedosuper)));
            } else {
                this.\u00d500000 = new F(0, 0, 0);
                this.\u00d200000[0] = 0;
                this.\u00d200000[1] = 0;
            }
        }
        catch (D d5) {
            // empty catch block
        }
    }

    public boolean \u00d200000(helden.framework.E.F f2) {
        if (f2 == null) {
            return false;
        }
        if (this.\u00d5o0000.contains(f2)) {
            return true;
        }
        for (helden.framework.E.F f3 : this.OO0000) {
            if (f3 != f2) continue;
            return true;
        }
        for (helden.framework.E.F f3 : this.public) {
            if (f3 != f2) continue;
            return true;
        }
        for (helden.framework.E.F f3 : this.\u00f5o0000) {
            if (f3 != f2) continue;
            return true;
        }
        return false;
    }

    public void \u00d800000(OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2) {
        for (int i2 = 0; i2 < 3; ++i2) {
            if (this.O\u00d20000[i2] != null) {
                float f2;
                int n;
                E e = this.O\u00d20000[i2].super();
                int n2 = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.privatedosuper);
                int n3 = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.returnwhilesuper);
                if (this.\u00d5O0000(i2).thisnew()) {
                    this.\u00d5O0000(i2).\u00d6o0000().toString();
                }
                if (e.equals(E.returnnewString)) {
                    n = new A(13, 3).o00000(n2);
                    if (n < 1) {
                        n = 0;
                    }
                    f2 = 0.1f * (float)n;
                    this.\u00d4O0000[i2] = new oooo_0(this.\u00d5O0000(i2).\u00d6o0000().o00000(0) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(0) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(1) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(1) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(2) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(2) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(3) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(3) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(4) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(4) * f2));
                    continue;
                }
                if (e.equals(E.\u00d5\u00d4\u00d8000)) {
                    n = new A(13, 3).o00000(n2);
                    f2 = 0.1f * (float)n;
                    this.\u00d4O0000[i2] = new oooo_0(this.\u00d5O0000(i2).\u00d6o0000().o00000(0) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(0) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(1) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(1) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(2) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(2) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(3) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(3) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(4) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(4) * f2));
                    continue;
                }
                if (e.equals(E.\u00d5\u00d6\u00d8000)) {
                    n = new A(13, 5).o00000(n2);
                    f2 = 0.1f * (float)n;
                    this.\u00d4O0000[i2] = new oooo_0(this.\u00d5O0000(i2).\u00d6o0000().o00000(0) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(0) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(1) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(1) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(2) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(2) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(3) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(3) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(4) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(4) * f2));
                    continue;
                }
                if (e.equals(E.\u00d3\u00d5\u00d8000)) {
                    n = new A(12, 3).o00000(n2);
                    f2 = 0.1f * (float)n;
                    this.\u00d4O0000[i2] = new oooo_0(this.\u00d5O0000(i2).\u00d6o0000().o00000(0) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(0) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(1) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(1) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(2) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(2) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(3) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(3) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(4) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(4) * f2));
                    continue;
                }
                if (e.equals(E.\u00d4\u00d4\u00d8000)) {
                    n = new A(12, 3).o00000(n3);
                    f2 = 0.1f * (float)n;
                    this.\u00d4O0000[i2] = new oooo_0(this.\u00d5O0000(i2).\u00d6o0000().o00000(0) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(0) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(1) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(1) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(2) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(2) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(3) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(3) * f2), this.\u00d5O0000(i2).\u00d6o0000().o00000(4) + Math.round((float)this.\u00d5O0000(i2).\u00d6o0000().o00000(4) * f2));
                    continue;
                }
                this.\u00d4O0000[i2] = this.\u00d5O0000(i2).\u00d6o0000();
                continue;
            }
            this.\u00d4O0000[i2] = null;
        }
    }

    public void o00000(OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2) {
        for (int i2 = 0; i2 < 3; ++i2) {
            if (this.O\u00d20000[i2] != null) {
                E e = this.O\u00d20000[i2].super();
                int n = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.privatedosuper);
                if (this.\u00d5O0000(i2).thisnew()) {
                    this.\u00f400000[i2] = this.\u00d5O0000(i2).\u00d8o0000();
                    continue;
                }
                if (e.equals(E.returnnewString)) {
                    this.\u00f400000[i2] = this.\u00d5O0000(i2).\u00d8o0000().o00000(new A(13, 3).o00000(n));
                    continue;
                }
                if (e.equals(E.\u00d5\u00d4\u00d8000)) {
                    this.\u00f400000[i2] = this.\u00d5O0000(i2).\u00d8o0000().o00000(new A(13, 3).o00000(n));
                    continue;
                }
                if (e.equals(E.\u00d5\u00d6\u00d8000)) {
                    this.\u00f400000[i2] = this.\u00d5O0000(i2).\u00d8o0000().o00000(new A(13, 5).o00000(n));
                    continue;
                }
                if (e.equals(E.\u00d3\u00d5\u00d8000)) {
                    this.\u00f400000[i2] = this.\u00d5O0000(i2).\u00d8o0000().o00000(new A(12, 3).o00000(n));
                    continue;
                }
                this.\u00f400000[i2] = this.\u00d5O0000(i2).\u00d8o0000();
                continue;
            }
            this.\u00f400000[i2] = null;
        }
    }

    public int \u00d2O0000() {
        return this.o00000;
    }

    public int \u00d500000() {
        return this.\u00d2o0000;
    }

    public int \u00d300000() {
        return this.intsuper.\u00f600000();
    }

    public String \u00f600000(int n) {
        return this.\u00d600000[n - 1];
    }

    public String newsuper(int n) {
        if (this.\u00d4O0000[n] == null) {
            return "";
        }
        return this.\u00d4O0000[n].toString();
    }

    public String \u00d8O0000(int n) {
        if (this.\u00f400000[n] == null) {
            return "";
        }
        return this.\u00f400000[n].toString();
    }

    public helden.framework.E.F \u00d500000(int n) {
        int n2 = n - 1;
        helden.framework.E.F f2 = this.OO0000[n2];
        return f2;
    }

    public if \u00f500000(int n) {
        return this.O\u00d20000[n - 1];
    }

    public int null(int n) {
        return this.\u00d2O0000[n];
    }

    public int returnsuper() {
        return this.Object;
    }

    public String oo0000(int n) {
        return this.\u00f4O0000[n - 1];
    }

    public String \u00d6O0000(int n) {
        StringBuffer stringBuffer = new StringBuffer();
        stringBuffer.append(" (");
        if (n < 2 && this.void) {
            stringBuffer.append("1-BK ");
        } else if (n > 1 && n < 4 && this.\u00f5O0000) {
            stringBuffer.append("2-BK ");
        }
        if (this.\u00f4O0000[n].equals("rechts")) {
            stringBuffer.append("R)");
        } else {
            stringBuffer.append("L)");
        }
        return stringBuffer.toString();
    }

    public int private() {
        return this.\u00f6o0000;
    }

    public int returnsuper(int n) {
        return this.oO0000[n];
    }

    public int \u00d8O0000() {
        return this.o\u00d20000;
    }

    public E \u00f5O0000() {
        if (this.o\u00d20000 < 1) {
            return null;
        }
        return this.O\u00d20000[this.o\u00d20000 - 1].super();
    }

    public helden.framework.E.F \u00f8O0000(int n) {
        int n2 = n - 1;
        helden.framework.E.F f2 = this.public[n2];
        return f2;
    }

    public helden.framework.e.oooo_0 \u00d3O0000(int n) {
        return this.\u00d5O0000[n - 1];
    }

    public int String(int n) {
        return this.\u00d4o0000[n];
    }

    public int \u00d200000(int n) throws B {
        if (this.oO0000(n).\u00d5\u00d50000().o00000(0) == -99) {
            throw new B("Waffe hat keine Parade");
        }
        return this.\u00d2\u00d20000[n];
    }

    public int \u00f6O0000() {
        return this.\u00d200000[0];
    }

    public int \u00d800000() {
        return this.\u00d200000[1];
    }

    public String null() {
        return this.\u00d500000.toString();
    }

    public int \u00d5O0000() {
        return this.interfacesuper[0];
    }

    public int String() {
        return this.interfacesuper[1];
    }

    public String \u00f600000() {
        return this.\u00f500000.toString();
    }

    public int for() {
        return this.intsuper.\u00d2O0000();
    }

    public ArrayList<helden.framework.E.F> oO0000() {
        return this.\u00d5o0000;
    }

    public helden.framework.E.F \u00f800000(int n) {
        int n2 = n - 1;
        helden.framework.E.F f2 = null;
        if (this.\u00d5o0000.size() > n2) {
            f2 = this.\u00d5o0000.get(n2);
        }
        return f2;
    }

    public String \u00d600000() {
        return "";
    }

    public helden.framework.E.F \u00f5O0000(int n) {
        int n2 = n - 1;
        helden.framework.E.F f2 = this.\u00f5o0000[n2];
        return f2;
    }

    public int for(int n) {
        return this.supersuper[n];
    }

    public int \u00d800000(int n) {
        int n2 = n - 1;
        if (this.\u00d6o0000[n2] != null) {
            return this.\u00d6o0000[n2];
        }
        return 0;
    }

    public int \u00d600000(int n) {
        return this.\u00f4o0000[n];
    }

    public String o00000(int n, OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2) {
        int n2 = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.privatedosuper);
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(I.o\u00d50000) ? this.oo0000(n + 1).equals("rechts") && !oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.\u00f6\u00d6\u00d5000.toString()) : this.oo0000(n + 1).equals("links") && !oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.\u00f6\u00d6\u00d5000.toString())) {
            return this.\u00d3O0000(n + 1).\u00d200000().\u00d500000().toString();
        }
        return this.\u00d3O0000(n + 1).\u00d200000().\u00d500000().o00000(this.\u00d3O0000(n + 1).\u00d200000().\u00d200000().o00000(n2)).toString();
    }

    public int private(int n) {
        int n2 = n - 1;
        if (this.\u00f600000[n2] != null) {
            return this.\u00f600000[n2];
        }
        return 0;
    }

    public helden.framework.E.C.B \u00f800000() {
        return this.intsuper;
    }

    public boolean \u00d6O0000() {
        return this.void;
    }

    public boolean \u00f500000() {
        return this.\u00f5O0000;
    }

    public boolean o00000(int n) {
        if (n < 0 || n > 4) {
            throw new RuntimeException("Ung\u00fcltige Nahkamfwaffen Nummer");
        }
        if (n == 0 || n == 1) {
            return this.\u00d6O0000();
        }
        return this.\u00f500000();
    }

    public boolean newsuper() {
        return this.oo0000;
    }

    public boolean o00000() {
        return this.\u00d6O0000;
    }

    public boolean \u00f6O0000(int n) {
        return this.o\u00d20000 == n;
    }

    public boolean \u00d200000() {
        return this.float;
    }

    public void o00000(while while_) {
        this.dosuper = while_;
    }

    public void \u00d300000(boolean bl) {
        this.\u00d6O0000 = bl;
    }

    public void \u00d200000(int n, String string) {
        this.dosuper.\u00d300000();
        this.\u00d600000[n - 1] = string;
    }

    public void \u00d200000(boolean bl) {
        this.dosuper.\u00d300000();
        this.void = bl;
    }

    public void o00000(boolean bl) {
        this.dosuper.\u00d300000();
        this.\u00f5O0000 = bl;
    }

    public void \u00d300000(int n, helden.framework.E.F f2) {
        int n2 = n - 1;
        this.OO0000[n2] = f2;
        this.O\u00d20000[n2] = f2 == null ? null : if.super(f2).get(0);
    }

    public void o00000(int n, if if_) {
        this.O\u00d20000[n - 1] = if_;
    }

    public void o00000(int n, String string) {
        this.dosuper.\u00d300000();
        this.\u00f4O0000[n - 1] = string;
    }

    public void \u00d300000(int n) {
        this.dosuper.\u00d300000();
        this.o\u00d20000 = n;
    }

    public void \u00d200000(int n, helden.framework.E.F f2) {
        this.dosuper.\u00d300000();
        int n2 = n - 1;
        this.public[n2] = f2;
        this.\u00d5O0000[n2] = f2 == null ? null : helden.framework.e.oooo_0.o00000(f2).get(0);
    }

    public void o00000(int n, helden.framework.e.oooo_0 oooo_02) {
        this.\u00d5O0000[n - 1] = oooo_02;
    }

    public void o00000(helden.framework.E.F f2) {
        this.dosuper.\u00d300000();
        this.\u00d5o0000.add(f2);
    }

    public void String(int n, helden.framework.E.F f2) {
        this.dosuper.\u00d300000();
        int n2 = n - 1;
        if (n > this.\u00d5o0000.size()) {
            this.\u00d5o0000.add(f2);
        } else {
            this.\u00d5o0000.add(n2, f2);
        }
    }

    public void o00000(int n, helden.framework.E.F f2) {
        this.dosuper.\u00d300000();
        int n2 = n - 1;
        this.\u00f5o0000[n2] = f2;
    }

    public void o00000(int n, int n2) {
        this.dosuper.\u00d300000();
        int n3 = n - 1;
        this.\u00d6o0000[n3] = new Integer(n2);
    }

    public void \u00d200000(int n, int n2) {
        this.dosuper.\u00d300000();
        int n3 = n - 1;
        this.\u00f600000[n3] = new Integer(n2);
    }

    public boolean \u00d3O0000() {
        for (helden.framework.E.F f2 : this.public) {
            if (f2 == null) continue;
            return true;
        }
        for (helden.framework.E.F f2 : this.OO0000) {
            if (f2 == null) continue;
            return true;
        }
        for (helden.framework.E.F f2 : this.\u00f5o0000) {
            if (f2 == null) continue;
            return true;
        }
        return this.\u00d5o0000.size() > 0;
    }

    private void \u00f8O0000() {
        int n;
        if (this.void) {
            n = -2;
            if (this.public[0].toString().equals(this.public[1].toString())) {
                n = 0;
            } else if (this.\u00d5O0000[0].o00000().equals(this.\u00d5O0000[1].o00000())) {
                n = -1;
            }
            this.\u00d4o0000[0] = this.\u00d4o0000[0] + n;
            this.\u00d2\u00d20000[0] = this.\u00d2\u00d20000[0] + n;
            this.\u00d4o0000[1] = this.\u00d4o0000[1] + n;
            this.\u00d2\u00d20000[1] = this.\u00d2\u00d20000[1] + n;
        }
        if (this.\u00f5O0000) {
            n = -2;
            if (this.public[2].toString().equals(this.public[3].toString())) {
                n = 0;
            } else if (this.\u00d5O0000[2].o00000().equals(this.\u00d5O0000[3].o00000())) {
                n = -1;
            }
            this.\u00d4o0000[2] = this.\u00d4o0000[2] + n;
            this.\u00d2\u00d20000[2] = this.\u00d2\u00d20000[2] + n;
            this.\u00d4o0000[3] = this.\u00d4o0000[3] + n;
            this.\u00d2\u00d20000[3] = this.\u00d2\u00d20000[3] + n;
        }
    }

    private void \u00d200000(OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2) {
        for (int i2 = 0; i2 < 3; ++i2) {
            if (this.O\u00d20000[i2] == null || this.\u00d5O0000(i2) == null) continue;
            E e = this.O\u00d20000[i2].super();
            int n = this.intsuper.\u00f600000() + this.\u00d5O0000(i2).\u00f5o0000().get(0).\u00d2\u00d80000();
            try {
                if (!oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.Oo0000().contains(e) && oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d300000(e) >= 0) {
                    this.\u00d2O0000[i2] = n < 0 ? oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(e) : oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(e) - n;
                    if (e.toString().equals(E.\u00d5\u00d4\u00d8000.toString()) && this.OO0000[i2] != null && this.OO0000[i2].OO0000().equals("Schneidzahn")) {
                        int n2 = i2;
                        this.\u00d2O0000[n2] = this.\u00d2O0000[n2] - 1;
                    }
                    if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000((oo0o_0)e).isEmpty()) continue;
                    for (String d2 : oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000((oo0o_0)e)) {
                        if (d2 == null || this.OO0000[i2] == null || !d2.equals(this.OO0000[i2].toString())) continue;
                        int n3 = i2;
                        this.\u00d2O0000[n3] = this.\u00d2O0000[n3] + 2;
                    }
                    continue;
                }
                Iterator<Object> iterator = e.\u00d4\u00d80000().iterator();
                this.\u00d2O0000[i2] = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d3\u00d30000().\u00f600000() - 5;
                while (iterator.hasNext()) {
                    try {
                        E e2 = iterator.next();
                        int n4 = this.intsuper.\u00f600000() + e2.\u00d2\u00d80000();
                        int n5 = 0;
                        if (!oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.Oo0000().contains(e2) && oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d300000(e2) >= 0) {
                            n5 = n4 < 0 ? oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(e2) : oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(e2) - n4 / 2;
                            n5 -= 5;
                        }
                        if (n5 < this.\u00d2O0000[i2]) continue;
                        this.\u00d2O0000[i2] = n5;
                    }
                    catch (D d2) {}
                }
                continue;
            }
            catch (D d3) {
                // empty catch block
            }
        }
    }

    private void \u00d600000(OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2) {
        for (int i2 = 0; i2 < 5; ++i2) {
            if (this.\u00d5O0000[i2] == null) continue;
            E e = this.\u00d5O0000[i2].o00000();
            int n = this.intsuper.\u00f600000() + e.\u00d2\u00d80000();
            int n2 = this.oO0000(i2).\u00d200000().o00000(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d3\u00d30000().do(b_0.privatedosuper));
            if (n2 > 0) {
                n2 = 0;
            }
            if (!this.oO0000(i2).\u00f6\u00d40000().contains(e)) {
                this.\u00d5O0000[i2].o00000(this.oO0000(i2).\u00f6\u00d40000().get(0));
                e = this.\u00d5O0000[i2].o00000();
            }
            try {
                if (!oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.Oo0000().contains(e) && oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d300000(e) >= 0) {
                    if (n < 0) {
                        this.\u00d4o0000[i2] = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(e);
                        this.\u00d2\u00d20000[i2] = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(e);
                        this.\u00d400000[i2] = 0;
                    } else {
                        this.\u00d4o0000[i2] = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(e) - n / 2;
                        this.\u00d2\u00d20000[i2] = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(e) - (n + 1) / 2;
                        this.\u00d400000[i2] = (n + 1) / 2;
                    }
                    this.\u00d4o0000[i2] = this.oO0000(i2).\u00d5\u00d50000().new(this.\u00d4o0000[i2]);
                    this.\u00d2\u00d20000[i2] = this.oO0000(i2).\u00d5\u00d50000().o00000(this.\u00d2\u00d20000[i2]);
                    int n3 = this.o00000(e, this.\u00f4O0000[i2], oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2);
                    int n4 = i2;
                    this.\u00d4o0000[n4] = this.\u00d4o0000[n4] + (n2 + n3);
                    int n5 = i2;
                    this.\u00d2\u00d20000[n5] = this.\u00d2\u00d20000[n5] + (n2 + n3);
                    if (this.\u00d6o0000[i2] != null && this.\u00d800000(i2 + 1) > 0 && this.\u00f5O0000(this.\u00d800000(i2 + 1)) != null && this.\u00d600000[this.\u00d800000(i2 + 1) - 1].equals(helden.framework.E.B.super(helden.framework.E.B.\u00d300000))) {
                        this.\u00d4o0000[i2] = this.\u00d2O0000(this.\u00d800000(i2 + 1) - 1).\u00f5\u00d20000().new(this.\u00d4o0000[i2]);
                    }
                    if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000((oo0o_0)e).isEmpty()) continue;
                    for (String string : oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000((oo0o_0)e)) {
                        if (!string.equals(this.public[i2].toString())) continue;
                        int n6 = i2;
                        this.\u00d4o0000[n6] = this.\u00d4o0000[n6] + 1;
                        int n7 = i2;
                        this.\u00d2\u00d20000[n7] = this.\u00d2\u00d20000[n7] + 1;
                    }
                    continue;
                }
                Iterator<E> iterator = e.\u00d4\u00d80000().iterator();
                this.\u00d4o0000[i2] = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.\u00f8\u00d8\u00d2000) - 2;
                this.\u00d2\u00d20000[i2] = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.ifwhilesuper) - 3;
                this.\u00d4o0000[i2] = this.oO0000(i2).\u00d5\u00d50000().new(this.\u00d4o0000[i2]);
                this.\u00d2\u00d20000[i2] = this.oO0000(i2).\u00d5\u00d50000().o00000(this.\u00d2\u00d20000[i2]);
                int n8 = i2;
                this.\u00d4o0000[n8] = this.\u00d4o0000[n8] + n2;
                int n9 = i2;
                this.\u00d2\u00d20000[n9] = this.\u00d2\u00d20000[n9] + n2;
                int n10 = this.intsuper.\u00f600000();
                if (n10 > 0) {
                    int n11 = i2;
                    this.\u00d4o0000[n11] = this.\u00d4o0000[n11] - n10 / 2;
                    int n12 = i2;
                    this.\u00d2\u00d20000[n12] = this.\u00d2\u00d20000[n12] - (n10 + 1) / 2;
                    this.\u00d400000[i2] = (n10 + 1) / 2;
                } else {
                    this.\u00d400000[i2] = 0;
                }
                while (iterator.hasNext()) {
                    E e2 = iterator.next();
                    int n13 = this.intsuper.\u00f600000() + e2.\u00d2\u00d80000();
                    int n14 = 0;
                    int n15 = 0;
                    int n16 = 0;
                    try {
                        if (!oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.Oo0000().contains(e2) && oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d300000(e2) >= 0) {
                            if (n13 < 0) {
                                n14 = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(e2);
                                n15 = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(e2);
                            } else {
                                n14 = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(e2) - n13 / 2;
                                n15 = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(e2) - (n13 + 1) / 2;
                                n16 = (n13 + 1) / 2;
                            }
                            n14 = this.oO0000(i2).\u00d5\u00d50000().new(n14);
                            n15 = this.oO0000(i2).\u00d5\u00d50000().o00000(n15);
                            n14 -= 2;
                            n15 -= 3;
                            n14 += n2;
                            n15 += n2;
                            if (this.\u00d6o0000[i2] != null && this.\u00d800000(i2 + 1) > 0 && this.\u00f5O0000(this.\u00d800000(i2 + 1)) != null && this.\u00d600000[this.\u00d800000(i2 + 1) - 1].equals(helden.framework.E.B.super(helden.framework.E.B.\u00d300000))) {
                                n14 = this.\u00d2O0000(this.\u00d800000(i2 + 1) - 1).\u00f5\u00d20000().new(n14);
                            }
                        }
                    }
                    catch (D d2) {
                        // empty catch block
                    }
                    if (n14 < this.\u00d4o0000[i2] || n15 < this.\u00d2\u00d20000[i2]) continue;
                    int n17 = this.o00000(e, this.\u00f4O0000[i2], oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2);
                    this.\u00d4o0000[i2] = n14;
                    this.\u00d2\u00d20000[i2] = n15;
                    int n18 = i2;
                    this.\u00d4o0000[n18] = this.\u00d4o0000[n18] + n17;
                    int n19 = i2;
                    this.\u00d2\u00d20000[n19] = this.\u00d2\u00d20000[n19] + n17;
                    this.\u00d400000[i2] = n16;
                }
                continue;
            }
            catch (D d3) {
                // empty catch block
            }
        }
        this.\u00f8O0000();
    }

    private void \u00d500000(OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2) {
        int n;
        int n2 = -9;
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.\u00d5\u00d4\u00d4000.toString())) {
            n2 = -4;
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.\u00f8\u00d3\u00d8000.toString())) {
            n2 = -1;
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.\u00f6\u00d3\u00d8000.toString())) {
            n2 = 2;
        }
        int n3 = -1;
        int n4 = -1;
        for (n = 0; n < this.\u00d6o0000.length; ++n) {
            if (this.\u00d6o0000[n] != null && this.\u00d6o0000[n] == 1) {
                n3 = n;
                continue;
            }
            if (this.\u00d6o0000[n] == null || this.\u00d6o0000[n] != 2) continue;
            n4 = n;
        }
        if (this.\u00f5o0000[0] != null && n3 > -1 && this.\u00d600000[0].equals(helden.framework.E.B.super(helden.framework.E.B.\u00f600000))) {
            if (this.\u00f8O0000(n3 + 1) != null) {
                try {
                    this.supersuper[0] = this.String(n3) + ((void)this.\u00f5o0000[0].o00000(helden.framework.E.B.\u00d300000, 0)).\u00f5\u00d20000().o00000();
                    this.\u00f4o0000[0] = n2 + this.\u00d200000(n3) + ((void)this.\u00f5o0000[0].o00000(helden.framework.E.B.\u00d300000, 0)).\u00f5\u00d20000().new();
                }
                catch (Exception exception) {
                    this.supersuper[0] = 0;
                    this.\u00f4o0000[0] = 0;
                }
            } else {
                this.supersuper[0] = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.\u00f8\u00d8\u00d2000) + ((void)this.\u00f5o0000[0].o00000(helden.framework.E.B.\u00d300000, 0)).\u00f5\u00d20000().o00000();
                this.\u00f4o0000[0] = n2 + oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.ifwhilesuper) + ((void)this.\u00f5o0000[0].o00000(helden.framework.E.B.\u00d300000, 0)).\u00f5\u00d20000().new();
            }
        }
        if (this.\u00f5o0000[1] != null && n4 > -1 && this.\u00d600000[1].equals(helden.framework.E.B.super(helden.framework.E.B.\u00f600000))) {
            if (this.\u00f8O0000(n4 + 1) != null) {
                try {
                    this.supersuper[1] = this.String(n4) + ((void)this.\u00f5o0000[1].o00000(helden.framework.E.B.\u00d300000, 0)).\u00f5\u00d20000().o00000();
                    this.\u00f4o0000[1] = n2 + this.\u00d200000(n4);
                    n = ((void)this.\u00f5o0000[1].o00000(helden.framework.E.B.\u00d300000, 0)).\u00f5\u00d20000().new();
                    this.\u00f4o0000[1] = this.\u00f4o0000[1] + n;
                }
                catch (Exception exception) {
                    this.supersuper[1] = 0;
                    this.\u00f4o0000[1] = 0;
                }
            } else {
                this.supersuper[1] = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.\u00f8\u00d8\u00d2000) + ((void)this.\u00f5o0000[1].o00000(helden.framework.E.B.\u00d300000, 0)).\u00f5\u00d20000().o00000();
                this.\u00f4o0000[1] = n2 + oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.ifwhilesuper) + ((void)this.\u00f5o0000[1].o00000(helden.framework.E.B.\u00d300000, 0)).\u00f5\u00d20000().new();
            }
        }
    }

    private void \u00d200000(OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2, boolean bl) {
        Object object;
        Cloneable cloneable;
        Iterator<helden.framework.E.F> iterator = this.\u00d5o0000.iterator();
        float f2 = 0.0f;
        float f3 = 0.0f;
        float f4 = 0.0f;
        float f5 = 0.0f;
        float f6 = 0.0f;
        float f7 = 0.0f;
        float f8 = 0.0f;
        float f9 = 0.0f;
        float f10 = 0.0f;
        float f11 = 0.0f;
        float f12 = 0.0f;
        float f13 = 0.0f;
        float f14 = 0.0f;
        float f15 = 0.0f;
        float f16 = 0.0f;
        float f17 = 0.0f;
        float f18 = 0.0f;
        float f19 = 0.0f;
        float f20 = 0.0f;
        float f21 = 0.0f;
        int n = 0;
        double d2 = 0.0;
        double d3 = 0.0;
        boolean bl2 = false;
        Set set = null;
        if (this.Oo0000) {
            cloneable = (helden.framework.D.void)oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f5O0000().o00000(helden.framework.D.while.\u00d8\u00d3\u00d2000.toString());
            set = ((helden.framework.D.void)cloneable).nullObject();
        }
        while (iterator.hasNext()) {
            try {
                cloneable = iterator.next();
                helden.framework.E.C.B b = ((helden.framework.E.C.B)((helden.framework.E.F)cloneable).o00000(helden.framework.E.B.OO0000, 0)).private();
                if (set != null && !bl2) {
                    object = set.iterator();
                    while (object.hasNext()) {
                        if (!((helden.framework.E.F)cloneable).toString().equals(((helden.framework.E.F)object.next()).toString())) continue;
                        bl2 = true;
                    }
                }
                if (b.\u00d3O0000()) {
                    d2 += (double)b.\u00f600000() / (double)b.for();
                    d3 += (double)b.\u00d2O0000() / (double)b.for();
                    b.\u00f600000(0);
                    b.\u00d500000(0);
                }
                if (b.\u00f5O0000() && b.null() > 0) {
                    f13 = (float)((double)f13 + (double)b.\u00f8O0000() / 2.0);
                    f14 = (float)((double)f14 + (double)b.\u00f800000() / 2.0);
                    f15 = (float)((double)f15 + (double)b.newsuper() / 2.0);
                    f16 = (float)((double)f16 + (double)b.\u00f6O0000() / 2.0);
                    f17 = (float)((double)f17 + (double)b.\u00d6O0000() / 2.0);
                    f18 = (float)((double)f18 + (double)b.\u00d8O0000() / 2.0);
                    f19 = (float)((double)f19 + (double)b.\u00f500000() / 2.0);
                    f20 = (float)((double)f20 + (double)b.\u00d5O0000() / 2.0);
                } else {
                    f13 += (float)b.\u00f8O0000();
                    f14 += (float)b.\u00f800000();
                    f15 += (float)b.newsuper();
                    f16 += (float)b.\u00f6O0000();
                    f17 += (float)b.\u00d6O0000();
                    f18 += (float)b.\u00d8O0000();
                    f19 += (float)b.\u00f500000();
                    f20 += (float)b.\u00d5O0000();
                    n += b.null();
                }
                f2 += (float)b.\u00f8O0000();
                f3 += (float)b.\u00f800000();
                f4 += (float)b.newsuper();
                f5 += (float)b.\u00f6O0000();
                f6 += (float)b.\u00d6O0000();
                f7 += (float)b.\u00d8O0000();
                f8 += (float)b.\u00f500000();
                f9 += (float)b.\u00d5O0000();
                f10 += (float)b.oO0000();
                f11 += (float)b.\u00d2O0000();
                f12 += (float)b.\u00f600000();
            }
            catch (CloneNotSupportedException cloneNotSupportedException) {}
        }
        cloneable = Einstellungen.getInstance().getSeitenEinstellungen(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f4o0000());
        f21 = (f13 * 2.0f + f14 * 4.0f + f15 * 4.0f + f16 * 4.0f + f17 + f18 + f19 * 2.0f + f20 * 2.0f) / (float)((DruckEinstellungen)cloneable).getZonenRSTeiler() - (float)n;
        float f22 = (f2 * 2.0f + f3 * 4.0f + f4 * 4.0f + f5 * 4.0f + f6 + f7 + f8 * 2.0f + f9 * 2.0f) / 20.0f;
        f12 = (float)((double)f12 + d2);
        f11 += (float)((int)(d3 + 1.0E-4));
        if (bl) {
            f12 = f21;
            f11 = f22;
            f10 = f22;
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(I.ifwhile)) {
            object = (J)oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00d500000().\u00d300000(I.ifwhile);
            f2 += (float)((J)object).ObjectString();
            f3 += (float)((J)object).ObjectString();
            f4 += (float)((J)object).ObjectString();
            f5 += (float)((J)object).ObjectString();
            f6 += (float)((J)object).ObjectString();
            f7 += (float)((J)object).ObjectString();
            f8 += (float)((J)object).ObjectString();
            f9 += (float)((J)object).ObjectString();
            f10 += (float)((J)object).ObjectString();
            f11 += (float)((J)object).ObjectString();
        }
        if (bl2) {
            f12 -= 1.0f;
        } else if (this.classsuper && f12 > 0.0f) {
            f12 -= 1.0f;
        } else if (this.\u00f6O0000) {
            f12 -= 2.0f;
        }
        if (f12 < 0.0f) {
            f12 = 0.0f;
        }
        object = new int[]{Math.round(f2), Math.round(f3), Math.round(f4), Math.round(f5), Math.round(f6), Math.round(f7), Math.round(f8), Math.round(f9), Math.round(f10), Math.round(f11)};
        this.intsuper = new helden.framework.E.C.B((int[])object, Math.round(f12), false, n);
    }

    private void \u00f500000(OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2) {
        int n;
        int n2 = 0;
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.\u00d5\u00d4\u00d4000.toString())) {
            ++n2;
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.\u00f5\u00f4\u00d5000.toString())) {
            n2 += 2;
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.\u00d8\u00f4\u00d5000.toString())) {
            n2 += 2;
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.\u00f6oO000.toString())) {
            n2 += 2;
        }
        int n3 = -1;
        int n4 = -1;
        for (n = 0; n < this.\u00d6o0000.length; ++n) {
            if (this.\u00d6o0000[n] != null && this.\u00d6o0000[n] == 1) {
                n3 = n;
                continue;
            }
            if (this.\u00d6o0000[n] == null || this.\u00d6o0000[n] != 2) continue;
            n4 = n;
        }
        if (this.\u00f5o0000[0] != null) {
            n = 0;
            if (n3 >= 0 && this.\u00d5O0000[n3] != null) {
                n = Math.max(0, (this.\u00d2\u00d20000[n3] - 12) / 3);
                n -= this.\u00d400000[n3];
            }
            if (this.\u00d600000[0].equals(helden.framework.E.B.super(helden.framework.E.B.\u00d300000))) {
                this.\u00f4o0000[0] = n + n2 + oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.ifwhilesuper) + ((void)this.\u00f5o0000[0].o00000(helden.framework.E.B.\u00d300000, 0)).\u00f5\u00d20000().new();
            }
        }
        if (this.\u00f5o0000[1] != null) {
            n = 0;
            if (n4 >= 0 && this.\u00d5O0000[n4] != null) {
                n = Math.max(0, (this.\u00d2\u00d20000[n4] - 12) / 3);
                n -= this.\u00d400000[n4];
            }
            if (this.\u00d600000[1].equals(helden.framework.E.B.super(helden.framework.E.B.\u00d300000))) {
                this.\u00f4o0000[1] = n + n2 + oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(b_0.ifwhilesuper) + ((void)this.\u00f5o0000[1].o00000(helden.framework.E.B.\u00d300000, 0)).\u00f5\u00d20000().new();
            }
        }
    }

    private void \u00d300000(OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2) {
        this.Oo0000 = false;
        this.classsuper = false;
        this.\u00f6O0000 = false;
        this.oo0000 = false;
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f5O0000().\u00d200000(helden.framework.D.while.\u00d5\u00d3\u00d2000.toString())) {
            this.\u00f6O0000 = true;
        } else if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f5O0000().\u00d200000(helden.framework.D.while.\u00d6\u00d3\u00d2000.toString())) {
            this.classsuper = true;
        } else if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f5O0000().\u00d200000(helden.framework.D.while.\u00d8\u00d3\u00d2000.toString())) {
            this.Oo0000 = true;
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f5O0000().\u00d200000(helden.framework.D.while.\u00f5o\u00f5000.toString())) {
            this.oo0000 = true;
        }
    }

    private helden.framework.E.C.E \u00d5O0000(int n) {
        return this.O\u00d20000[n].\u00d200000();
    }

    private int o00000(E e, String string, OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2) {
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(I.ifnullsuper)) {
            return 0;
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.newObjectObject.toString())) {
            return 0;
        }
        int n = -9;
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.\u00d5\u00d4\u00d4000.toString())) {
            n = -6;
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.\u00d5\u00d4\u00d4000.toString()) && oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.new(helden.framework.D.while.\u00f6\u00d6\u00d5000.toString())) {
            n = -3;
        }
        if (e.equals(E.\u00d8\u00d6\u00d8000) || e.equals(E.\u00d5\u00d5\u00d8000) || e.equals(E.\u00f8\u00d5\u00d8000) || e.equals(E.ifthisString) || e.equals(E.\u00f4\u00d3\u00d8000) || e.equals(E.\u00d8\u00d5\u00d8000) || e.equals(E.o\u00d6\u00d8000) || e.equals(E.\u00d3\u00d4\u00d8000) || e.equals(E.o\u00d5\u00d8000)) {
            return 0;
        }
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.o00000(I.o\u00d50000)) {
            if (string.equals("links")) {
                return 0;
            }
            return n;
        }
        if (string.equals("rechts")) {
            return 0;
        }
        return n;
    }

    private helden.framework.E.C.A oO0000(int n) {
        return this.\u00d5O0000[n].\u00d200000();
    }

    private void \u00d2O0000(int n) {
        return (void)this.\u00f5o0000[n].o00000(helden.framework.E.B.\u00d300000, 0);
    }

    private void null(OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2) {
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f5O0000().\u00d200000(helden.framework.D.while.\u00d3\u00d4\u00f6000.toString())) {
            a_0 a_02 = (a_0)oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.\u00f5O0000().o00000(helden.framework.D.while.\u00d3\u00d4\u00f6000.toString());
            for (int i2 = 0; i2 < 5; ++i2) {
                for (R r : a_02.nullObject()) {
                    ArrayList<String> arrayList = new ArrayList<String>();
                    U u2 = null;
                    int n = 0;
                    int n2 = 0;
                    int n3 = 0;
                    double d2 = 0.0;
                    for (int i3 = 0; i3 < r.o00000(); ++i3) {
                        String string;
                        R r2;
                        Object object = r.o00000(i3);
                        if (object instanceof helden.framework.E.F || object instanceof String) {
                            arrayList.add(object.toString());
                        }
                        if (object instanceof E) {
                            u2 = (E)object;
                        }
                        if (!(object instanceof R) || !((r2 = (R)object).o00000(0) instanceof oooo_4)) continue;
                        oooo_4 oooo_42 = (oooo_4)((Object)r2.o00000(0));
                        if (oooo_42.name().equals(oooo_4.int.name())) {
                            n = Integer.parseInt(r2.o00000(2) + "");
                        }
                        if (oooo_42.name().equals(oooo_4.interface.name())) {
                            n2 = Integer.parseInt(r2.o00000(2) + "");
                        }
                        if (oooo_42.name().equals(oooo_4.super.name())) {
                            n3 = Integer.parseInt(r2.o00000(2) + "");
                        }
                        if (oooo_42.name().equals(oooo_4.\u00d8O0000.name())) {
                            if ((r2.o00000(2) + "").equals("+10%")) {
                                d2 = 1.1;
                            }
                            if ((r2.o00000(2) + "").equals("+20%")) {
                                d2 = 1.2;
                            }
                        }
                        if (!oooo_42.name().equals(oooo_4.\u00d800000.name()) && !oooo_42.name().equals(oooo_4.\u00d600000.name())) continue;
                        if (r2.o00000(2) instanceof R) {
                            string = ((R)r2.o00000(2)).o00000(0).toString();
                            arrayList.add(string);
                            continue;
                        }
                        string = r2.o00000(2).toString();
                        int n4 = string.indexOf(",");
                        arrayList.add(string.substring(1, n4));
                    }
                    if (this.\u00d5O0000[i2] != null && this.\u00d5O0000[i2].o00000().toString().equals(u2.toString())) {
                        if (this.\u00f8O0000(i2 + 1) == null || !arrayList.contains(this.\u00f8O0000(i2 + 1).toString())) continue;
                        int n5 = i2;
                        this.\u00d4o0000[n5] = this.\u00d4o0000[n5] + n;
                        int n6 = i2;
                        this.\u00d2\u00d20000[n6] = this.\u00d2\u00d20000[n6] + n2;
                        this.oO0000[i2] = n3;
                        if (i2 >= this.\u00d600000.length || !this.\u00d600000[i2].equals(helden.framework.E.B.super(helden.framework.E.B.\u00f600000))) continue;
                        int n7 = i2;
                        this.\u00f4o0000[n7] = this.\u00f4o0000[n7] + n2;
                        continue;
                    }
                    if (i2 >= 3 || this.O\u00d20000[i2] == null || !this.O\u00d20000[i2].super().toString().equals(u2.toString()) || this.\u00d500000(i2 + 1) == null || !arrayList.contains(this.\u00d500000(i2 + 1).toString())) continue;
                    int n8 = i2;
                    this.\u00d2O0000[n8] = this.\u00d2O0000[n8] + n;
                    this.\u00d4O0000[i2] = this.\u00d4O0000[i2].o00000(d2);
                }
            }
        }
    }
}

