/*
 * Decompiled with CFR 0.152.
 */
package helden.framework.D.OoOO;

import helden.framework.D.F;
import helden.framework.D.while;
import helden.framework.HeldenMath;
import helden.framework.OOoO.OoOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO;
import helden.framework.OOoO.R;
import helden.framework.held.Object.floatsuper;
import helden.framework.oooo.oooo_0;
import java.util.ArrayList;
import java.util.Arrays;

public class whilesuper
extends F {
    private static final int \u00d6\u00d5\u00f8000 = 7;
    private static final int Stringthisreturn = 30;
    private ArrayList \u00d5\u00d5\u00f8000 = new ArrayList<String>(Arrays.asList("Luft", "Erz", "Humus", "Eis", "Wasser", "Feuer", ""));
    private OoOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO \u00d3\u00d5\u00f8000;

    public static int o00000(OoOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO ooOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO) {
        if (ooOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000()) {
            return 3;
        }
        if (ooOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.super()) {
            return 3;
        }
        return 2;
    }

    public static int O\u00d60000() {
        return 30;
    }

    public static int \u00d3\u00d60000() {
        return 7;
    }

    public whilesuper(OoOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO ooOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO) {
        super(while.\u00d3\u00d5\u00d3000.toString() + ": " + ooOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.toString(), 4, helden.framework.D.OoOO.whilesuper.o00000(ooOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO));
        this.\u00d3\u00d5\u00f8000 = ooOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO;
        if (ooOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000()) {
            this.privateObject()[0] = helden.framework.D.OoOO.whilesuper.\u00d500000(helden.framework.D.OoOO.whilesuper.\u00d3\u00d60000());
            this.privateObject()[1] = helden.framework.D.OoOO.whilesuper.\u00d500000(helden.framework.D.OoOO.whilesuper.O\u00d60000());
            this.privateObject()[2] = helden.framework.D.OoOO.whilesuper.\u00d500000(0);
            this.o00000("Qualit\u00e4t", "Beschw\u00f6rungsschwierigkeit", "konkreter Name der Wesenheit");
        } else if (ooOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.super()) {
            this.privateObject()[0] = this.whileString();
            this.privateObject()[1] = helden.framework.D.OoOO.whilesuper.\u00d500000(helden.framework.D.OoOO.whilesuper.\u00d3\u00d60000());
            this.privateObject()[2] = helden.framework.D.OoOO.whilesuper.\u00d500000(0);
            this.o00000("Element", "Qualit\u00e4t", "konkreter Name der Wesenheit");
        } else {
            this.privateObject()[0] = helden.framework.D.OoOO.whilesuper.\u00d500000(helden.framework.D.OoOO.whilesuper.\u00d3\u00d60000());
            this.privateObject()[1] = helden.framework.D.OoOO.whilesuper.\u00d500000(0);
            this.o00000("Qualit\u00e4t", "konkreter Name der Wesenheit");
        }
        this.o00000(new oooo_0(){

            @Override
            public String super(R r) {
                if (whilesuper.this.\u00d3\u00d5\u00f8000.\u00d200000()) {
                    return java.lang.String.format("Q%s BS%02d %s", r.o00000(0), r.o00000(1), r.o00000(2));
                }
                if (whilesuper.this.\u00d3\u00d5\u00f8000.super()) {
                    return java.lang.String.format("%s Q%s %s", r.o00000(0), r.o00000(1), r.o00000(2));
                }
                return java.lang.String.format("Q%s %s", r.o00000(0), r.o00000(1));
            }
        });
        this.\u00f4\u00d40000();
    }

    @Override
    public Object clone() throws CloneNotSupportedException {
        whilesuper whilesuper2 = new whilesuper(this.\u00d3\u00d5\u00f8000);
        this.o00000(this, whilesuper2);
        whilesuper2.\u00d3\u00d5\u00f8000 = this.\u00d3\u00d5\u00f8000;
        return whilesuper2;
    }

    @Override
    public boolean equals(Object object) {
        if (object == null) {
            return false;
        }
        return this.toString().equals(object.toString());
    }

    @Override
    public int o00000(R r) {
        int n = this.\u00d3\u00d5\u00f8000.\u00d200000() ? HeldenMath.runde(0.5f * ((Integer)r.o00000(0)).floatValue() * ((Integer)r.o00000(1)).floatValue()) : (this.\u00d3\u00d5\u00f8000.super() ? (Integer)r.o00000(1) * Integer.parseInt(this.\u00d3\u00d5\u00f8000.\u00d400000()) : (Integer)r.o00000(0) * Integer.parseInt(this.\u00d3\u00d5\u00f8000.\u00d400000()));
        return n;
    }

    public OoOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO o\u00d60000() {
        return this.\u00d3\u00d5\u00f8000;
    }

    @Override
    public String o00000(R r, floatsuper floatsuper2, boolean bl) {
        int n = this.o\u00d60000().\u00d200000() ? 2 : (this.o\u00d60000().super() ? 2 : 1);
        if (r.o00000(n) == null || r.o00000(n).equals("")) {
            return "Es feht eine Beschreibung des Wahren Names";
        }
        return null;
    }

    private ArrayList whileString() {
        return this.\u00d5\u00d5\u00f8000;
    }
}

