/*
 * Decompiled with CFR 0.152.
 */
package helden.framework.int;

import helden.framework.C.I;
import helden.framework.C.OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO;
import helden.framework.D.while;
import helden.framework.OoOO.E;
import helden.framework.OoOO.N;
import helden.framework.OoOO.voidsuper;
import helden.framework.int.OoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO;
import helden.framework.oOoO.W;
import helden.framework.oOoO.publicsuper;
import helden.framework.oooo.a_2;
import helden.framework.oooo.b_0;
import helden.framework.oooo.c_0;
import helden.framework.oooo.c_1;
import helden.framework.oooo.d_0;
import helden.framework.oooo.i_0;
import helden.framework.oooo.o0oo_1;
import helden.framework.oooo.oo0o_0;
import helden.framework.oooo.oooo_5;
import java.util.ArrayList;
import java.util.Set;

public class do
extends OoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
implements c_0 {
    private OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO \u00f4\u00f6\u00f4O00;
    private boolean \u00d8\u00f6\u00f4O00;
    private Set<oo0o_0> \u00f5\u00f6\u00f4O00;
    private a_2 returnthisfloat;
    private oooo_5 \u00d5\u00f6\u00f4O00;

    public do() {
    }

    public do(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2, Set<oo0o_0> set) {
        this.\u00f4\u00f6\u00f4O00 = oOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2;
        this.\u00f5\u00f6\u00f4O00 = set;
        if (oOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.newifsuper)) {
            this.returnthisfloat = new a_2(I.\u00f5\u00d30000, 3);
        }
    }

    @Override
    public void bestimmeTalentwerte(int n) {
    }

    public OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO \u00f4\u00d3O000() {
        return this.\u00f4\u00f6\u00f4O00;
    }

    public W<Object> O\u00d4O000() {
        ArrayList<Object> arrayList = new ArrayList<Object>();
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.o\u00d2\u00d2000)) {
            arrayList.addAll(this.dofloat());
            return new i_0(arrayList, this);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.returnifsuper)) {
            arrayList.add(new d_0(voidsuper.o\u00f6\u00d6000, 1));
            arrayList.add(new a_2(I.\u00d4oo000, 2));
            return new i_0(arrayList, this);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d5\u00d2\u00d2000)) {
            arrayList.add(new d_0(voidsuper.thisinterfaceObject, 2));
            arrayList.add(this.o00000(voidsuper.StringObjectObject));
            return new i_0(arrayList, this);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00f5o\u00d2000)) {
            arrayList.add(this.o00000(voidsuper.thisintObject));
            arrayList.add(new a_2(I.\u00d4\u00d5o000, 2));
            arrayList.add(new a_2(I.OO\u00d2000, 2));
            return new i_0(arrayList, this);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d4\u00d2\u00d2000)) {
            arrayList.add(new d_0(voidsuper.\u00d4\u00f8\u00d5000, 1));
            arrayList.add(new publicsuper(b_0.thispublicsuper, 1));
            return new i_0(arrayList, this);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.O\u00d2\u00d2000)) {
            arrayList.add(this.o00000(voidsuper.forclassObject));
            arrayList.add(new oooo_5(while.iffloatObject.toString(), 2));
            return new i_0(arrayList, this);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d3\u00d2\u00d2000)) {
            arrayList.add(new d_0(voidsuper.returnforObject, 1));
            arrayList.add(new d_0(voidsuper.\u00d30\u00d8000, 2));
            return new i_0(arrayList, this);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d8\u00d2\u00d2000)) {
            arrayList.add(new d_0(voidsuper.\u00d5\u00d5\u00d6000, 2));
            arrayList.add(this.o00000(voidsuper.\u00f5\u00f5\u00d6000));
            return new i_0(arrayList, this);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00f8o\u00d2000)) {
            arrayList.add(new d_0(voidsuper.\u00f5\u00d8\u00d5000, 1));
            arrayList.add(this.o00000(voidsuper.\u00f8\u00f8\u00d6000));
            return new i_0(arrayList, this);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00f4o\u00d2000)) {
            arrayList.add(new d_0(voidsuper.\u00d4\u00d8\u00d6000, 1));
            arrayList.add(this.o00000(voidsuper.\u00d5\u00d5\u00d5000));
            return new i_0(arrayList, this);
        }
        throw new c_1();
    }

    public I \u00f5\u00d3O000() {
        return this.returnthisfloat.new();
    }

    public String intfloat() {
        return this.\u00d5\u00f6\u00f4O00.\u00d800000();
    }

    public int \u00d6\u00d3O000() {
        if (this.\u00f6\u00d3O000()) {
            return this.returnthisfloat.o00000();
        }
        return this.\u00d5\u00f6\u00f4O00.return();
    }

    public boolean \u00d4\u00d3O000() {
        return this.interfacefloat() && !this.\u00d8\u00f6\u00f4O00;
    }

    @Override
    public void o00000(o0oo_1 o0oo_12) {
        o0oo_1 o0oo_13;
        if (o0oo_12 instanceof d_0) {
            o0oo_13 = (d_0)o0oo_12;
            this.setTalentwert(((d_0)o0oo_13).\u00d400000(), ((d_0)o0oo_13).\u00d300000());
        }
        if (o0oo_12 instanceof publicsuper) {
            o0oo_13 = (publicsuper)o0oo_12;
            this.setzeModifizierteEigenschaft(((publicsuper)o0oo_13).\u00d500000());
        }
        if (o0oo_12 instanceof oooo_5) {
            this.\u00d5\u00f6\u00f4O00 = (oooo_5)o0oo_12;
        }
        if (o0oo_12 instanceof a_2) {
            this.returnthisfloat = (a_2)o0oo_12;
        }
        this.\u00d8\u00f6\u00f4O00 = true;
    }

    public boolean \u00d5\u00d3O000() {
        return this.\u00d5\u00f6\u00f4O00 != null;
    }

    public boolean \u00f6\u00d3O000() {
        return this.returnthisfloat != null;
    }

    @Override
    protected void setzeModifikationen() {
        if (this.\u00f4\u00f6\u00f4O00 == null) {
            return;
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00f4\u00d2\u00d2000)) {
            this.\u00d200000(voidsuper.StringclassObject);
            this.setTalentwert(voidsuper.returnforObject, -1);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.o\u00d2\u00d2000)) {
            this.setTalentwert(voidsuper.thisvoidObject, -1);
            this.setTalentwert(voidsuper.returnforObject, -1);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.privateintsuper)) {
            this.setTalentwert(voidsuper.returnprivateObject, 1);
            this.setTalentwert(voidsuper.o\u00f6\u00d6000, -1);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.returnifsuper)) {
            this.setTalentwert(voidsuper.\u00d5\u00d5\u00d5000, -1);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d5\u00d2\u00d2000)) {
            this.setTalentwert(voidsuper.\u00d30\u00d8000, -1);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00f5o\u00d2000)) {
            this.setTalentwert(voidsuper.\u00d40\u00d6000, -1);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d4\u00d2\u00d2000)) {
            this.setTalentwert(voidsuper.\u00d4\u00d8\u00d6000, -1);
            if (this.getModifizierteEigenschaft() != null) {
                this.putModifikator(this.getModifizierteEigenschaft(), 1);
            }
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.O\u00d2\u00d2000)) {
            this.setTalentwert(E.\u00f4\u00d6\u00d8000, -1);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d3\u00d2\u00d2000)) {
            this.setTalentwert(voidsuper.\u00d4\u00f8\u00d5000, -1);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d8\u00d2\u00d2000)) {
            this.setTalentwert(E.\u00f5\u00d3\u00d8000, -1);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00f8o\u00d2000)) {
            this.setTalentwert(voidsuper.\u00d4\u00f8\u00d5000, -1);
        }
        if (this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00f4o\u00d2000)) {
            this.setTalentwert(voidsuper.\u00d4\u00f8\u00d5000, -1);
        }
    }

    private ArrayList<d_0> dofloat() {
        ArrayList<d_0> arrayList = new ArrayList<d_0>();
        for (E e : N.floatsuper().interface()) {
            arrayList.add(this.o00000(e));
        }
        return arrayList;
    }

    private d_0 o00000(voidsuper voidsuper2) {
        if (this.\u00f5\u00f6\u00f4O00.contains(voidsuper2)) {
            return new d_0(voidsuper2, 2);
        }
        return new d_0(voidsuper2, 1);
    }

    private boolean interfacefloat() {
        if (this.\u00f4\u00f6\u00f4O00 == null) {
            return false;
        }
        return !this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00f4\u00d2\u00d2000) && !this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.privateintsuper) && !this.\u00f4\u00f6\u00f4O00.equals(OOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.newifsuper);
    }

    private void \u00d200000(voidsuper voidsuper2) {
        if (this.\u00f5\u00f6\u00f4O00.contains(voidsuper2)) {
            this.setTalentwert(voidsuper2, 2);
        } else {
            this.setTalentwert(voidsuper2, 1);
        }
    }
}

