/*
 * Decompiled with CFR 0.152.
 */
package helden.framework.held.B.B;

import helden.framework.Einstellungen;
import helden.framework.held.B.B.A.F;
import helden.framework.held.B.B.A.I;
import helden.framework.held.B.B.A.J;
import helden.framework.held.B.B.A.OoOO;
import helden.framework.held.B.B.A.String;
import helden.framework.held.B.B.A.null;
import helden.framework.held.B.B.A.o0OO;
import helden.framework.held.B.B.OoOO.A;
import helden.framework.held.B.B.OoOO.B;
import helden.framework.held.B.B.OoOO.C;
import helden.framework.held.B.B.OoOO.G;
import helden.framework.held.B.B.OoOO.K;
import helden.framework.held.B.B.OoOO.N;
import helden.framework.held.B.B.OoOO.O0oO;
import helden.framework.held.B.B.OoOO.OooO;
import helden.framework.held.B.B.OoOO.o0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO;
import helden.framework.held.B.B.OoOO.return;
import helden.framework.held.OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;

/*
 * Illegal identifiers - consider using --renameillegalidents true
 */
public final class oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO {
    private static oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO \u00d500000;
    private List<helden.framework.held.B.B.G> o00000 = new ArrayList<helden.framework.held.B.B.G>();
    private List<helden.framework.held.B.B.G> String = new ArrayList<helden.framework.held.B.B.G>();
    private OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO \u00d200000;
    private Graphics \u00d300000 = null;

    public static oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO \u00d300000() {
        if (\u00d500000 == null) {
            \u00d500000 = new oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO();
        }
        return \u00d500000;
    }

    public void \u00d500000() {
        if (this.\u00d200000 == null) {
            return;
        }
        this.\u00d400000().clear();
        helden.framework.held.Object.C.\u00d800000(this.\u00d200000);
        this.return().clear();
        helden.framework.held.B.B.G g2 = null;
        if (Einstellungen.getInstance().isNeueBoegen()) {
            g2 = new String(this.\u00d200000);
            this.o00000.add(g2);
            g2 = new J(this.\u00d200000);
            this.o00000.add(g2);
            g2 = new I(this.\u00d200000);
            this.o00000.add(g2);
            g2 = new helden.framework.held.B.B.A.C(this.\u00d200000, 0);
            this.o00000.add(g2);
            g2 = new helden.framework.held.B.B.A.oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO(this.\u00d200000, 0);
            this.o00000.add(g2);
            g2 = new helden.framework.held.B.B.A.G(this.\u00d200000, 0);
            this.o00000.add(g2);
            g2 = new null(this.\u00d200000, 0);
            this.o00000.add(g2);
            g2 = new OoOO(this.\u00d200000, 0);
            this.o00000.add(g2);
            g2 = new F(this.\u00d200000);
            this.o00000.add(g2);
            g2 = new o0OO(this.\u00d200000);
            this.o00000.add(g2);
        }
        if (Einstellungen.getInstance().isAlteBoegen()) {
            g2 = new N(this.\u00d200000);
            this.o00000.add(g2);
            g2 = new OooO(this.\u00d200000);
            this.o00000.add(g2);
            g2 = new G(this.\u00d200000);
            this.o00000.add(g2);
            g2 = new C(this.\u00d200000, 0);
            this.o00000.add(g2);
            g2 = new return(this.\u00d200000);
            this.o00000.add(g2);
            g2 = new B(this.\u00d200000);
            this.o00000.add(g2);
            g2 = new K(this.\u00d200000);
            this.o00000.add(g2);
            g2 = new A(this.\u00d200000, 0);
            this.o00000.add(g2);
            g2 = new O0oO(this.\u00d200000, 0);
            this.o00000.add(g2);
            g2 = new o0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO(this.\u00d200000, 0);
            this.o00000.add(g2);
        }
        for (helden.framework.held.B.B.G g3 : this.o00000) {
            this.\u00d400000().addAll(g3.\u00d500000());
        }
    }

    public List<helden.framework.held.B.B.G> return() {
        return this.o00000;
    }

    public Graphics new() {
        if (this.\u00d300000 == null) {
            BufferedImage bufferedImage = new BufferedImage(450, 680, 1);
            this.\u00d300000 = bufferedImage.getGraphics();
            this.\u00d300000.setFont(this.o00000(9));
        }
        return this.\u00d300000;
    }

    public List<helden.framework.held.B.B.G> \u00d400000() {
        return this.String;
    }

    public void o00000() {
        this.\u00d300000 = null;
    }

    public void o00000(OooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2) {
        if (oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2 != this.\u00d200000) {
            this.\u00d200000 = oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2;
            this.\u00d500000();
        }
    }

    protected Font o00000(int n) {
        return helden.framework.held.B.B.G.new(n);
    }
}

