/*
 * Decompiled with CFR 0.152.
 */
package helden.framework.e.super;

import helden.framework.E.B;
import helden.framework.E.C.A;
import helden.framework.E.C.void;
import helden.framework.E.G;
import helden.framework.E.O0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO;
import helden.framework.E.OoOO.D;
import helden.framework.E.OoOO.F;
import helden.framework.E.OoOO.OoOO;
import helden.framework.E.OoOO.null;
import helden.framework.E.OoOO.oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO;
import helden.framework.OoOO.E;
import helden.framework.oooo.oooo_1;
import java.util.ArrayList;

/*
 * Illegal identifiers - consider using --renameillegalidents true
 * Renamed from helden.framework.E.super.ooOO
 */
public final class oooo_2 {
    public static ArrayList<helden.framework.E.F> \u00d400000(Object object) {
        if (object instanceof O0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO) {
            ArrayList<helden.framework.E.F> arrayList = new ArrayList<helden.framework.E.F>();
            helden.framework.E.F f2 = new helden.framework.E.F("Bock", B.\u00f600000, 120.0f, 8000, 1, new oooo_1("AA", 95), new G[0]);
            f2.o00000(new void(new null(-1, 1), new D(0), 0));
            f2.o00000(new A(new F(1, 6, 2), new OoOO(new helden.framework.E.OoOO.A(10, 5), new null(0, 0)), 10, E.\u00f4\u00d6\u00d8000, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(0), -1));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Buckler", B.\u00f600000, 40.0f, 4000, 1, new oooo_1("AA", 95), new G[0]);
            f2.o00000(new void(new null(0, 1), new D(0), 0));
            A a2 = new A(new F(1, 6, 0), new OoOO(new helden.framework.E.OoOO.A(11, 4), new null(-2, -1)), 5, E.\u00f4\u00d6\u00d8000, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(0), -1);
            a2.String(true);
            f2.o00000(a2);
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Buckler (Vollmetall)", B.\u00f600000, 60.0f, 6000, 1, new oooo_1("AA", 95), new G[0]);
            f2.o00000(new void(new null(0, 2), new D(-2), 0));
            a2 = new A(new F(1, 6, 1), new OoOO(new helden.framework.E.OoOO.A(11, 4), new null(-2, 0)), 5, E.\u00f4\u00d6\u00d8000, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(-2), -1);
            f2.o00000(a2);
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Drachenklaue", B.\u00f600000, 200.0f, 35000, 1, new oooo_1("AA", 98), new G[0]);
            f2.o00000(new void(new null(-2, 1), new D(0), 0));
            f2.o00000(new A(new F(1, 6, 2), new OoOO(new helden.framework.E.OoOO.A(12, 3), new null(0, 0)), 10, E.\u00f4\u00d6\u00d8000, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(0), -1));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Gro\u00dfschild", B.\u00d300000, 200.0f, 10000, 1, new oooo_1("AA", 96), new G[0]);
            f2.o00000(new void(new null(-2, 5), new D(2), -2));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Hakendolch", B.\u00f600000, 50.0f, 9000, 1, new oooo_1("AA", 61), new G[0]);
            f2.o00000(new void(new null(-1, 3), new D(-2), 0));
            f2.o00000(new A(new F(1, 6, 1), new OoOO(new helden.framework.E.OoOO.A(12, 4), new null(0, 1)), 60, E.nullsuperString, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000, oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d600000), new D(-2), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Holzschild", B.\u00d300000, 140.0f, 4000, 1, new oooo_1("AA", 96), new G[0]);
            f2.o00000(new void(new null(-1, 3), new D(3), -1));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Hummerschere", B.\u00f600000, 70.0f, 25000, 1, new oooo_1("AA", 69), new G[0]);
            f2.o00000(new void(new null(-2, 1), new D(4), -1));
            f2.o00000(new A(new F(1, 6, 2), new OoOO(new helden.framework.E.OoOO.A(12, 4), new null(0, -1)), 0, E.\u00f4\u00d6\u00d8000, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(4), -1));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Holzschild (verst\u00e4rkt)", B.\u00d300000, 160.0f, 5000, 1, new oooo_1("AA", 96), new G[0]);
            f2.o00000(new void(new null(-2, 3), new D(0), -1));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Kriegsf\u00e4cher", B.\u00f600000, 50.0f, 25000, 1, new oooo_1("AA", 80), new G[0]);
            f2.o00000(new void(new null(0, 2), new D(3), 1));
            f2.o00000(new A(new F(1, 6, 2), new OoOO(new helden.framework.E.OoOO.A(12, 5), new null(0, 1)), 40, E.\u00f5\u00d3\u00d8000, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(3), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Kriegsf\u00e4cher (Dornen)", B.\u00f600000, 65.0f, 30000, 1, new oooo_1("AA", 80), new G[0]);
            f2.o00000(new void(new null(0, 2), new D(1), 1));
            f2.o00000(new A(new F(1, 6, 2), new OoOO(new helden.framework.E.OoOO.A(12, 5), new null(0, 1)), 40, E.\u00f5\u00d3\u00d8000, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(1), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Kriegsf\u00e4cher (Vollmetall)", B.\u00f600000, 60.0f, 30000, 1, new oooo_1("AA", 80), new G[0]);
            f2.o00000(new void(new null(0, 2), new D(1), 1));
            f2.o00000(new A(new F(1, 6, 2), new OoOO(new helden.framework.E.OoOO.A(12, 5), new null(0, 1)), 40, E.\u00f5\u00d3\u00d8000, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(1), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Langdolch", B.\u00f600000, 30.0f, 4500, 1, new oooo_1("AA", 66), new G[0]);
            f2.o00000(new void(new null(0, 1), new D(0), 0));
            a2 = new A(new F(1, 6, 2), new OoOO(new helden.framework.E.OoOO.A(12, 4), new null(0, 0)), 40, E.nullsuperString, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(1), 0);
            a2.\u00d300000(E.\u00d4\u00d5\u00d8000);
            f2.o00000(a2);
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Lederschild", B.\u00d300000, 80.0f, 3000, 1, new oooo_1("AA", 96), new G[0]);
            f2.o00000(new void(new null(-1, 3), new D(5), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Lederschild (gro\u00df)", B.\u00d300000, 120.0f, 7500, 1, new oooo_1("AA", 96), new G[0]);
            f2.o00000(new void(new null(-1, 4), new D(6), -1));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Linkhand", B.\u00f600000, 30.0f, 9000, 1, new oooo_1("AA", 62), new G[0]);
            f2.o00000(new void(new null(0, 2), new D(0), 1));
            f2.o00000(new A(new F(1, 6, 1), new OoOO(new helden.framework.E.OoOO.A(12, 5), new null(0, 1)), 30, E.nullsuperString, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(0), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Linkhand mit Klingenf\u00e4nger", B.\u00f600000, 35.0f, 10500, 1, new oooo_1("AA", 62), new G[0]);
            f2.o00000(new void(new null(0, 2), new D(0), 1));
            f2.o00000(new A(new F(1, 6, 1), new OoOO(new helden.framework.E.OoOO.A(12, 5), new null(0, 1)), 30, E.nullsuperString, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(0), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Linkhand und Klingenbrecher", B.\u00f600000, 40.0f, 11500, 1, new oooo_1("AA", 62), new G[0]);
            f2.o00000(new void(new null(0, 2), new D(0), 1));
            f2.o00000(new A(new F(1, 6, 1), new OoOO(new helden.framework.E.OoOO.A(12, 5), new null(0, 1)), 30, E.nullsuperString, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(0), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Mattenschild", B.\u00d300000, 100.0f, 6000, 1, new oooo_1("AA", 97), new G[0]);
            f2.o00000(new void(new null(-1, 4), new D(6), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Panzerarm", B.\u00f600000, 220.0f, 14000, 1, new oooo_1("AA", 97), new G[0]);
            f2.o00000(new void(new null(-2, 1), new D(-2), -1));
            f2.o00000(new A(new F(1, 6, 2), new OoOO(new helden.framework.E.OoOO.A(11, 3), new null(0, 0)), 10, E.\u00f4\u00d6\u00d8000, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(-2), -1));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Thorwaler Rundschild", B.\u00d300000, 180.0f, 6000, 1, new oooo_1("AA", 98), new G[0]);
            f2.o00000(new void(new null(-2, 4), new D(3), -1));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Turmschild", B.\u00d300000, 280.0f, 12000, 1, new oooo_1("AA", 98), new G[0]);
            f2.o00000(new void(new null(-5, 7), new D(1), -3));
            arrayList.add(f2);
            return arrayList;
        }
        return new ArrayList<helden.framework.E.F>();
    }

    public static ArrayList<helden.framework.E.F> super(Object object) {
        if (object instanceof O0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO) {
            ArrayList<helden.framework.E.F> arrayList = new ArrayList<helden.framework.E.F>();
            helden.framework.E.F f2 = new helden.framework.E.F("Legion\u00e4rsschild", B.\u00d300000, 200.0f, 6000, 1, new oooo_1("DDZ", 96), new G[0]);
            f2.o00000(new void(new null(-2, 4), new D(2), -1));
            arrayList.add(f2);
            return arrayList;
        }
        return new ArrayList<helden.framework.E.F>();
    }

    public static ArrayList<helden.framework.E.F> \u00d200000(Object object) {
        if (object instanceof O0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO) {
            ArrayList<helden.framework.E.F> arrayList = new ArrayList<helden.framework.E.F>();
            helden.framework.E.F f2 = new helden.framework.E.F("Abishai-Tartsche", B.\u00d300000, 40.0f, 1200, 1, new oooo_1("MA", 133), new G[0]);
            f2.o00000(new void(new null(0, 1), new D(4), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Blutb\u00fcffel-Schild", B.\u00d300000, 180.0f, 3500, 1, new oooo_1("MA", 133), new G[0]);
            f2.o00000(new void(new null(-2, 5), new D(2), -2));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Faustschild (Metall)", B.\u00f600000, 60.0f, 1800, 1, new oooo_1("MA", 133), new G[0]);
            f2.o00000(new void(new null(0, 2), new D(-2), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Flechtschild", B.\u00d300000, 100.0f, 1000, 1, new oooo_1("MA", 133), new G[0]);
            f2.o00000(new void(new null(-1, 4), new D(6), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Myrmidonen-Reiterschild", B.\u00d300000, 100.0f, 2500, 1, new oooo_1("MA", 134), new G[0]);
            f2.o00000(new void(new null(-2, 5), new D(5), -2));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Myrmidonenschild", B.\u00d300000, 160.0f, 2500, 1, new oooo_1("MA", 135), new G[0]);
            f2.o00000(new void(new null(-1, 3), new D(5), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Myrmidonen-Setzschild", B.\u00d300000, 320.0f, 4500, 1, new oooo_1("MA", 135), new G[0]);
            f2.o00000(new void(new null(-5, 7), new D(1), -3));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Sto\u00dfbuckler", B.\u00f600000, 80.0f, 3200, 1, new oooo_1("MA", 135), new G[0]);
            f2.o00000(new void(new null(0, 0), new D(-1), -2));
            arrayList.add(f2);
            f2.o00000(new A(new F(1, 6, 3), new OoOO(new helden.framework.E.OoOO.A(10, 5), new null(0, 0)), 25, E.\u00f4\u00d6\u00d8000, oooo_2.super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.\u00d200000), new D(-2), -1));
            return arrayList;
        }
        return new ArrayList<helden.framework.E.F>();
    }

    public static ArrayList<helden.framework.E.F> \u00d300000(Object object) {
        if (object instanceof O0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO) {
            ArrayList<helden.framework.E.F> arrayList = new ArrayList<helden.framework.E.F>();
            helden.framework.E.F f2 = new helden.framework.E.F("Achteckiger Bronzeschild", B.\u00d300000, 40.0f, 0, 1, new oooo_1("WnT", 86), new G[0]);
            f2.o00000(new void(new null(0, 1), new D(0), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Gro\u00dfes Achteck", B.\u00d300000, 160.0f, 0, 1, new oooo_1("WnT", 86), new G[0]);
            f2.o00000(new void(new null(-2, 3), new D(0), -1));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Memonhabitischer Lederschild", B.\u00d300000, 80.0f, 0, 1, new oooo_1("WnT", 86), new G[0]);
            f2.o00000(new void(new null(-1, 3), new D(5), 0));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("J\u00fcitischer Lederschild", B.\u00d300000, 120.0f, 0, 1, new oooo_1("WnT", 86), new G[0]);
            f2.o00000(new void(new null(-1, 4), new D(4), -1));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Laniaischer Reiterschild", B.\u00d300000, 200.0f, 0, 1, new oooo_1("WnT", 86), new G[0]);
            f2.o00000(new void(new null(-1, 4), new D(2), -2));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Conossischer Rundschild", B.\u00d300000, 240.0f, 0, 1, new oooo_1("WnT", 86), new G[0]);
            f2.o00000(new void(new null(-4, 6), new D(1), -3));
            arrayList.add(f2);
            f2 = new helden.framework.E.F("Rakshasaschild", B.\u00d300000, 360.0f, 0, 1, new oooo_1("WnT", 86), new G[0]);
            f2.o00000(new void(new null(-8, 10), new D(1), -5));
            arrayList.add(f2);
            return arrayList;
        }
        return new ArrayList<helden.framework.E.F>();
    }

    private static ArrayList<oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO> super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2) {
        ArrayList<oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO> arrayList = new ArrayList<oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO>();
        arrayList.add(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2);
        return arrayList;
    }

    private static ArrayList<oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO> super(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2, oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO3) {
        ArrayList<oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO> arrayList = new ArrayList<oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO>();
        arrayList.add(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO2);
        arrayList.add(oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO3);
        return arrayList;
    }

    private oooo_2() {
    }
}

