/*
 * Decompiled with CFR 0.152.
 */
package helden.framework.OOoO;

import helden.framework.EigeneErweiterungenMoeglich;
import helden.framework.OOoO.A;
import helden.framework.OOoO.o00O;
import helden.framework.held.object.oooo_0;
import helden.framework.oooo.oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0;
import java.util.ArrayList;

public class O
implements EigeneErweiterungenMoeglich {
    public static final O nullintString = new O("Adamantenhart", "Elementar (Erz)", "Beseelung der Quelle", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 2400);
    public static final O forclassString = new O("Blick durch die Wand", "Elementar (Erz)", "Hellsicht", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 200);
    public static final O \u00d4\u00d6\u00f4000 = new O("Dreifaches Gewicht", "Elementar (Erz)", "Beseelung der Quelle", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 5);
    public static final O \u00d8\u00f4\u00d8000 = new O("Elementare Waffe (Machira)", "Elementar (Erz)", "Elementare Manifestation", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 20);
    public static final O \u00d5O\u00f4000 = new O("Erzexplosion", "Elementar (Erz)", "Explosion", 12, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O StringfloatString = new O("Erzschild", "Elementar (Erz)", "Beseelung der Quelle", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O \u00d3\u00d3\u00f4000 = new O("Fluchtweg durch Stein", "Elementar (Erz)", "Transport durch Element", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d300000, 200);
    public static final O \u00d8\u00f4\u00f4000 = new O("Gegenstandsduplikat", "Elementar (Erz)", "Illusion", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O \u00d80\u00f4000 = new O("\u00d6ffnende Hand", "Elementar (Erz)", "Objektbewegung", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O StringObjectString = new O("Sandangriff", "Elementar (Erz)", "Schadenszauber", 12, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 3);
    public static final O \u00d8\u00f5\u00d8000 = new O("Sicherer Weg (W\u00fcste)", "Elementar (Erz)", "Wahrnehmung der Quelle", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 20);
    public static final O \u00d8\u00f8\u00d8000 = new O("Silberner Schutz", "Elementar (Erz)", "Beseelung der Quelle", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 3);
    public static final O forintString = new O("St\u00e4hlerne Faust", "Elementar (Erz)", "Transformation", 10, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 2);
    public static final O \u00d4\u00d2\u00f4000 = new O("(Waffe) zu Pflugschar", "Elementar (Erz)", "Verwandlung", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 200);
    public static final O returnforString = new O("Weg durch die W\u00fcste", "Elementar (Erz)", "\u00dcber Element gehen", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O forfloatString = new O("Werkzeug aus dem Nichts (Dietriche)", "Elementar (Erz)", "Elementare Manifestation", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 200);
    public static final O \u00d5\u00f4\u00d8000 = new O("W\u00fcstenschlaf", "Elementar (Erz)", "Transformation", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 1200);
    public static final O StringintString = new O("Ablenkung", "Elementar (Luft)", "Illusion", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 10);
    public static final O \u00d5\u00d6\u00f4000 = new O("Geschwindigkeitssteigerung", "Elementar (Luft)", "Beseelung der Quelle", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O o\u00d3\u00f4000 = new O("Das goldene Ohr", "Elementar (Luft)", "Hellsicht", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O \u00f5O\u00f4000 = new O("Federfall", "Elementar (Luft)", "Beseelung der Quelle", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 2);
    public static final O \u00d3\u00d2\u00f4000 = new O("Fliegen", "Elementar (Luft)", "Transport durch Element", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d300000, 20);
    public static final O \u00d40\u00f4000 = new O("Parfum", "Elementar (Luft)", "Illusion", 2, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 20);
    public static final O ififString = new O("Sturm", "Elementar (Luft)", "Kontrolle \u00fcber Element", 19, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 2400);
    public static final O ifnewString = new O("Tierillusion (L\u00f6we)", "Elementar (Luft)", "Illusion", 11, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 20);
    public static final O \u00d3\u00f4\u00d8000 = new O("Brandschutz", "Elementar (Feuer)", "Bann der Quelle", 1, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 2400);
    public static final O \u00f4o\u00f4000 = new O("Entz\u00fcnden", "Elementar (Feuer)", "Elementare Manifestation", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 10);
    public static final O \u00d4\u00f5\u00d8000 = new O("Feuerball", "Elementar (Feuer)", "Explosion", 13, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 10);
    public static final O \u00d30\u00f4000 = new O("Feuerhand", "Elementar (Feuer)", "Schadenszauber", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 3);
    public static final O \u00f5\u00f6\u00d8000 = new O("Licht", "Elementar (Feuer)", "Beseelung der Quelle", 8, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 10);
    public static final O \u00f8\u00f4\u00f4000 = new O("Schmiedefeuer", "Elementar (Feuer)", "Elementare Reinheit", 9, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 200);
    public static final O \u00d3o\u00f4000 = new O("Schutz vor Hitze", "Elementar (Feuer)", "Schutz vor Quelle", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 1200);
    public static final O o\u00d8\u00f4000 = new O("Verh\u00fclltes Feuer", "Elementar (Feuer)", "Verh\u00fcllung", 13, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O whilenullString = new O("Best\u00e4ndiges Wasser", "Elementar (Wasser)", "Fixierung", 10, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 2400);
    public static final O \u00f8\u00f6\u00d8000 = new O("Ertr\u00e4nken", "Elementar (Wasser)", "Elementare Manifestation", 8, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 8);
    public static final O returnifString = new O("K\u00fchles Wasser", "Elementar (Wasser)", "Elementare Manifestation", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 200);
    public static final O \u00d3\u00f5\u00f4000 = new O("Reinigung des Wassers", "Elementar (Wasser)", "Reinigung", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O \u00f5\u00d4\u00f4000 = new O("Wasseranalyse", "Elementar (Wasser)", "Analyse", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 1200);
    public static final O \u00f5\u00d5\u00f4000 = new O("Wasser finden", "Elementar (Wasser)", "Wahrnehmung der Quelle", 10, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 200);
    public static final O \u00d5\u00d8\u00d8000 = new O("Atemnot", "Elementar (Humus)", "Kontrolle \u00fcber Element", 11, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 5);
    public static final O \u00f5o\u00f4000 = new O("Ausdauer steigern", "Elementar (Humus)", "Beseelung der Quelle", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O \u00d5\u00d2\u00f4000 = new O("Blick in die Karten", "Elementar (Humus)", "Hellsicht", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 5);
    public static final O privatefloatString = new O("Blutheilung", "Elementar (Humus)", "Transfer", 8, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 2);
    public static final O \u00f8o\u00f4000 = new O("Cham\u00e4leonhaut", "Elementar (Humus)", "Verh\u00fcllung", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 5);
    public static final O \u00d4\u00d4\u00f4000 = new O("Das Auge des Anatomen", "Elementar (Humus)", "Wahrnehmung der Quelle", 2, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 1200);
    public static final O \u00f8\u00d6\u00f4000 = new O("Die Waffen des L\u00f6wen", "Elementar (Humus)", "Verwandlung", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 5);
    public static final O privatevoidString = new O("Durchhalteverm\u00f6gen", "Elementar (Humus)", "Beseelung der Quelle", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O OO\u00f4000 = new O("Fernabsprache", "Elementar (Humus)", "Kommunikation", 11, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d300000, 2400);
    public static final O o\u00f6\u00d8000 = new O("Fesselranken", "Elementar (Humus)", "Fixierung", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 10);
    public static final O newifString = new O("Fruchtbares Land", "Elementar (Humus)", "Transformation", 11, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 1200);
    public static final O o\u00f5\u00d8000 = new O("Giftheilung (10)", "Elementar (Humus)", "Reinigung", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O \u00f4\u00d5\u00f4000 = new O("Gro\u00dfer Heilzauber", "Elementar (Humus)", "Heilung/Wiederherstellung", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 1200);
    public static final O whileforString = new O("Kleiner Heilzauber", "Elementar (Humus)", "Heilung/Wiederherstellung", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O \u00d8\u00d3\u00f4000 = new O("K\u00f6rperuntersuchung", "Elementar (Humus)", "Analyse", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 200);
    public static final O \u00f8\u00d6\u00d8000 = new O("Konstitutionssteigerung", "Elementar (Humus)", "Beseelung der Quelle", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O \u00f5\u00f8\u00d8000 = new O("Kraft der Erde", "Elementar (Humus)", "Transfer", 12, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 2400);
    public static final O \u00f8\u00d5\u00f4000 = new O("Kurze Telepathie", "Elementar (Humus)", "Kommunikation", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O \u00d4\u00f6\u00d8000 = new O("Mit (Tierart) sprechen", "Elementar (Humus)", "Kommunikation", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.null, 20);
    public static final O \u00d5\u00f6\u00d8000 = new O("Pflanzenwachstum", "Elementar (Humus)", "Kontrolle \u00fcber Element", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 200);
    public static final O \u00d4\u00f4\u00f4000 = new O("Saubere Kleidung", "Elementar (Humus)", "Reinigung", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 20);
    public static final O \u00d3\u00d5\u00f4000 = new O("Verh\u00fclltes Gesicht", "Elementar (Humus)", "Verh\u00fcllung", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 10);
    public static final O \u00d3\u00d6\u00f4000 = new O("Wasseratmung", "Elementar (Humus)", "Verwandlung", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 200);
    public static final O \u00d8\u00f6\u00d8000 = new O("Weg durch die Dornen", "Elementar (Humus)", "\u00dcber Element gehen", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O \u00d50\u00f4000 = new O("Wellen des Fleisches", "Elementar (Humus)", "Kontrolle \u00fcber Element", 11, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 2);
    public static final O newStringString = new O("Winterschlaf", "Elementar (Humus)", "Kontrolle \u00fcber Element", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O \u00d3\u00d8\u00f4000 = new O("Abk\u00fchlung", "Elementar (Eis)", "Beseelung der Quelle", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 20);
    public static final O \u00f4\u00f4\u00f4000 = new O("Dunkelheit", "Elementar (Eis)", "Beseelung der Quelle", 10, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O returnnullString = new O("Elementarspeer (Eis)", "Elementar (Eis)", "Kontrolle \u00fcber Element", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 20);
    public static final O \u00d8\u00d8\u00d8000 = new O("Skulptur herstellen (Eis)", "Elementar (Eis)", "Kontrolle \u00fcber Element", 8, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 1200);
    public static final O \u00d4\u00d8\u00f4000 = new O("Statue aus (Eis)", "Elementar (Eis)", "Transformation", 10, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 10);
    public static final O \u00f80\u00f4000 = new O("Artefaktzerst\u00f6rung", "Kraft", "Antimagie", 12, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 2400);
    public static final O \u00f5\u00d8\u00f4000 = new O("Astralkonzentration", "Kraft", "Kontrolle \u00fcber Element", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.String, 24000);
    public static final O ifforString = new O("Astralkraft spenden", "Kraft", "Transfer", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 200);
    public static final O \u00d8\u00d4\u00f4000 = new O("Einfache Telekinese", "Kraft", "Objektbewegung", 11, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.null, 1);
    public static final O \u00d4\u00d3\u00f4000 = new O("Kurze Zauberanalyse", "Kraft", "Analyse", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.null, 5);
    public static final O \u00d4O\u00f4000 = new O("Lange Zauberanalyse", "Kraft", "Analyse", 8, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 200);
    public static final O \u00f4\u00f4\u00d8000 = new O("Teleport", "Kraft", "Transport durch Element", 15, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d300000, 10);
    public static final O \u00d3\u00d8\u00d8000 = new O("Verwandlung beenden (25 AsP)", "Kraft", "Antimagie", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O \u00f5\u00f5\u00d8000 = new O("Zauberbann (30 AsP)", "Kraft", "Antimagie", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 2400);
    public static final O \u00f50\u00f4000 = new O("Zaubertarnung", "Kraft", "Verh\u00fcllung", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 200);
    public static final O \u00d4\u00d5\u00f4000 = new O("Fessel der Aggression", "Aggression", "Kontrolle \u00fcber Gef\u00fchle", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 10);
    public static final O \u00f5\u00f4\u00d8000 = new O("Gelenkte Gewalt", "Aggression", "Kontrolle \u00fcber Gef\u00fchle", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 5);
    public static final O \u00f4\u00f8\u00d8000 = new O("Kampfinspiration", "Aggression", "Beseelung der Quelle", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 10);
    public static final O \u00d3\u00d4\u00f4000 = new O("Streitinspiration", "Aggression", "Beseelung der Quelle", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 10);
    public static final O \u00d5\u00f8\u00d8000 = new O("Analyse der Begierde", "Begierde", "Analyse", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 10);
    public static final O o\u00f8\u00d8000 = new O("D\u00fcstere Inspiration", "Begierde", "Beseelung der Quelle", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O newforString = new O("Inkarnation der Begierde", "Begierde", "Kontrolle \u00fcber Gef\u00fchle", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 200);
    public static final O O\u00f6\u00d8000 = new O("Mit (Gr\u00f6\u00dfenwahn) erf\u00fcllen", "Begierde", "Beseelung der Quelle", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O \u00f8\u00f5\u00d8000 = new O("Mit Pessimismus anstecken", "Begierde", "Kommunikation", 9, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 20);
    public static final O nullclassString = new O("Verlangen ausl\u00f6sen", "Begierde", "Kontrolle \u00fcber Gef\u00fchle", 12, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 5);
    public static final O \u00f5\u00f4\u00f4000 = new O("Angst erzeugen", "Endg\u00fcltigkeit", "Kontrolle \u00fcber Gef\u00fchle", 11, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 5);
    public static final O ifnullString = new O("Magischer Eid", "Endg\u00fcltigkeit", "Beseelung der Quelle", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 1200);
    public static final O returnreturnString = new O("Scheintod", "Endg\u00fcltigkeit", "Geistillusion", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 20);
    public static final O \u00f4\u00d3\u00f4000 = new O("Tradition der \u00dcberzeugung", "Endg\u00fcltigkeit", "Beseelung der Quelle", 9, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 200);
    public static final O \u00f5\u00d3\u00f4000 = new O("Traumbotschaft", "Endg\u00fcltigkeit", "Traumbesuch", 11, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 2400);
    public static final O \u00d8\u00d2\u00f4000 = new O("Anf\u00fchrer finden", "Erfolg", "Wahrnehmung der Quelle", 11, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 200);
    public static final O O\u00d8\u00f4000 = new O("Anf\u00fchrer der Truppen", "Erfolg", "Kommunikation", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 10);
    public static final O O\u00d6\u00f4000 = new O("Ehrenhaftes Duell", "Erfolg", "Kontrolle \u00fcber Gef\u00fchle", 11, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 5);
    public static final O \u00d4\u00f5\u00f4000 = new O("Herrschaft \u00fcber (Tierart)", "Erfolg", "Kontrolle \u00fcber Wesen", 9, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 10);
    public static final O \u00f40\u00f4000 = new O("Kurzer Befehl", "Erfolg", "Kontrolle \u00fcber Wesen", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O \u00f4\u00f5\u00d8000 = new O("Respektsperson", "Erfolg", "Kontrolle \u00fcber Gef\u00fchle", 10, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O \u00d5\u00d3\u00f4000 = new O("Typimitation (Brajansgardist)", "Erfolg", "Geistillusion", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O o\u00d4\u00f4000 = new O("Blick durch Illusionen", "Erkenntnis", "Beseelung der Quelle", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 10);
    public static final O \u00d8\u00d8\u00f4000 = new O("Blick in die Zukunft", "Erkenntnis", "Beseelung der Quelle", 0, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 2400);
    public static final O \u00d3\u00f5\u00d8000 = new O("Gespeichertes Bild", "Erkenntnis", "Kontrolle \u00fcber Gef\u00fchle", 9, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 200);
    public static final O \u00f5\u00d6\u00d8000 = new O("Klugheit steigern", "Erkenntnis", "Beseelung der Quelle", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O O\u00f8\u00d8000 = new O("Magische Aufkl\u00e4rung", "Erkenntnis", "Kommunikation", 8, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 5);
    public static final O ifreturnString = new O("Orientierung", "Erkenntnis", "Beseelung der Quelle", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O \u00d5o\u00f4000 = new O("Verst\u00e4ndnishilfe (Sprache)", "Erkenntnis", "Beseelung der Quelle", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 20);
    public static final O StringclassString = new O("Verwirrung des Geistes", "Erkenntnis", "Kontrolle \u00fcber Gef\u00fchle", 9, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 3);
    public static final O O\u00f4\u00f4000 = new O("Abgelenkter Geist", "Freiheit", "Kontrolle \u00fcber Gef\u00fchle", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 200);
    public static final O \u00d8o\u00f4000 = new O("Aufmunterung", "Freiheit", "Beseelung der Quelle", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 200);
    public static final O o\u00f5\u00f4000 = new O("Erneute Gedanken", "Freiheit", "Beseelung der Quelle", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 10);
    public static final O \u00d3\u00f4\u00f4000 = new O("Freiheit des Geistes", "Freiheit", "Kontrolle \u00fcber Gef\u00fchle", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 5);
    public static final O \u00f8\u00f4\u00d8000 = new O("Vernachl\u00e4ssigung", "Freiheit", "Kontrolle \u00fcber Wesen", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 10);
    public static final O whileifString = new O("Erf\u00fcllung mit Gl\u00fcckseligkeit", "Harmonie", "Beseelung der Quelle", 9, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O o\u00d5\u00f4000 = new O("Friedensstiftung", "Harmonie", "Kontrolle \u00fcber Gef\u00fchle", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 10);
    public static final O \u00d5\u00f4\u00f4000 = new O("Friedliche Stimmung", "Harmonie", "Beseelung der Quelle", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 200);
    public static final O o\u00f4\u00d8000 = new O("Magische Empathie", "Harmonie", "Beseelung der Quelle", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O \u00d5\u00f5\u00f4000 = new O("\u00dcberzeugung der Zufriedenheit", "Harmonie", "Beseelung der Quelle", 2, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O thisObjectString = new O("Kunstinspiration (Malen/Zeichnen)", "Kreativit\u00e4t", "Beseelung der Quelle", 2, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O \u00f4\u00d6\u00f4000 = new O("Leihen von Kreativit\u00e4t", "Kreativit\u00e4t", "Transfer", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O \u00d3O\u00f4000 = new O("Verst\u00e4ndnis der Mechanik", "Kreativit\u00e4t", "Beseelung der Quelle", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O O\u00f4\u00d8000 = new O("Einbildungen", "Wahnsinn", "Wahnsinn", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 20);
    public static final O \u00d8\u00f5\u00f4000 = new O("Kurzfristige Heilung des Wahnsinns", "Wahnsinn", "Kontrolle \u00fcber Gef\u00fchle", 9, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.String, 1200);
    public static final O \u00f4\u00d4\u00f4000 = new O("Zuf\u00e4llige Entscheidung", "Wahnsinn", "Beseelung der Quelle", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O o0\u00f4000 = new O("Bannzone", "Zauberei", "Bann der Quelle", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 20);
    public static final O privateclassString = new O("Schnelle Zauberst\u00e4rkung", "Zauberei", "Metamagie", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 5);
    public static final O privateintString = new O("Instruktion leihen", "Zauberei", "Transfer", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O ifStringString = new O("Traum teilen", "Zauberei", "Traumbesuch", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 200);
    public static final O newnullString = new O("Zauber entdecken", "Zauberei", "Wahrnehmung der Quelle", 8, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 20);
    public static final O \u00d8\u00d6\u00f4000 = new O("Zauberverbindung", "Zauberei", "Kommunikation", 8, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 20);
    public static final O O\u00d4\u00f4000 = new O("Zauber zur\u00fcckwerfen", "Zauberei", "Metamagie", 9, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 5);
    public static final O \u00f8\u00f8\u00d8000 = new O("D\u00e4monisches Feuer", "Tyakaar", "D\u00e4monische Manifestation", 9, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 20);
    public static final O forvoidString = new O("Imagin\u00e4re Folter", "Tyakaar", "Geistillusion", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O \u00f8O\u00f4000 = new O("Legitimatensinn", "Tyakaar", "Beseelung der Quelle", 2, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O \u00f8\u00d3\u00f4000 = new O("Verh\u00fcllung des Meuchlers", "Tyakaar", "Verh\u00fcllung", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O \u00d4\u00f4\u00d8000 = new O("Wahrheitszwang", "Tyakaar", "Kontrolle \u00fcber Gef\u00fchle", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 10);
    public static final O o\u00d2\u00f4000 = new O("Blutrausch ausl\u00f6sen", "Carafai", "Beseelung der Quelle", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O StringvoidString = new O("Massenmord", "Carafai", "Explosion", 11, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 20);
    public static final O \u00f4O\u00f4000 = new O("Unbesiegbarer K\u00e4mpfer", "Carafai", "Beseelung der Quelle", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 20);
    public static final O newreturnString = new O("Giftiges Wasser", "Galkuzul", "D\u00e4monische Manifestation", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 200);
    public static final O o\u00f4\u00f4000 = new O("Seeungeheuer rufen", "Galkuzul", "Kommunikation", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.String, 28800);
    public static final O thisvoidString = new O("Wassertentakel", "Galkuzul", "Kontrolle \u00fcber Element", 13, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 5);
    public static final O \u00f4\u00d2\u00f4000 = new O("Komplexe Telekinese", "Thesephai", "Objektbewegung", 11, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 10);
    public static final O O\u00d5\u00f4000 = new O("Sto\u00df", "Thesephai", "Objektbewegung", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f800000, 1);
    public static final O \u00f4\u00d8\u00d8000 = new O("Zwietracht s\u00e4en", "Thesephai", "Kontrolle \u00fcber Gef\u00fchle", 8, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 10);
    public static final O thisdoString = new O("Gruppenfesselung", "Avastada", "Fixierung", 12, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 2);
    public static final O \u00d8O\u00f4000 = new O("Objektkleber", "Avastada", "Fixierung", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 200);
    public static final O forObjectString = new O("Spinnenangriff", "Avastada", "Kontrolle \u00fcber Wesen", 9, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O \u00f4\u00f5\u00f4000 = new O("Altersaufschub", "Dya'Khol", "Beseelung der Quelle", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.String, 26400);
    public static final O \u00f4\u00f6\u00d8000 = new O("Lebender Alptraum", "Dya'Khol", "Geistillusion", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 5);
    public static final O \u00f5\u00d8\u00d8000 = new O("Knochensplitter", "Dya'Khol", "Schadenszauber", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 10);
    public static final O O0\u00f4000 = new O("Todeszauber", "Dya'Khol", "Schadenszauber", 2, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 10);
    public static final O privateObjectString = new O("Doppelg\u00e4nger", "Iryabaar", "Illusion", 13, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 3);
    public static final O \u00d4\u00f8\u00d8000 = new O("Einfache Unsichtbarkeit", "Iryabaar", "Verh\u00fcllung", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O oO\u00f4000 = new O("Neuer K\u00f6rper", "Iryabaar", "Verwandlung", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 2400);
    public static final O o\u00d8\u00d8000 = new O("Vollsensorisches Trugbild (Drache)", "Iryabaar", "Illusion", 20, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.String, 200);
    public static final O \u00f8\u00d4\u00f4000 = new O("Wissensdiebstahl", "Iryabaar", "Transfer", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 26400);
    public static final O whileStringString = new O("Herrschaft \u00fcber die Meute (Wolf)", "Naggarach", "Kontrolle \u00fcber Wesen", 10, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 10);
    public static final O O\u00f5\u00f4000 = new O("Lawine ausl\u00f6sen", "Naggarach", "Kontrolle \u00fcber Element", 10, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 200);
    public static final O \u00f5\u00d6\u00f4000 = new O("Rabiarverwandlung", "Naggarach", "Transformation", 11, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.String, 5);
    public static final O \u00d4o\u00f4000 = new O("D\u00e4monisches Schnurren", "Ghorgumor", "Beseelung der Quelle", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 20);
    public static final O thisintString = new O("Katzenjunges", "Ghorgumor", "Geistillusion", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f600000, 10);
    public static final O \u00d5\u00d4\u00f4000 = new O("Katzensprache", "Ghorgumor", "Kommunikation", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 10);
    public static final O \u00d4\u00d8\u00d8000 = new O("Khalyanars Angriffe", "Khalyanar", "Beseelung der Quelle", 14, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 20);
    public static final O \u00d5\u00d5\u00f4000 = new O("K\u00f6rperformung", "Khalyanar", "Kontrolle \u00fcber Element", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.String, 200);
    public static final O O\u00d2\u00f4000 = new O("Tierverwandlung (Maus)", "Khalyanar", "Verwandlung", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O oo\u00f4000 = new O("Diebstahlhinweis", "Xolovar", "Kommunikation", 9, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 2400);
    public static final O thisclassString = new O("Gier wecken", "Xolovar", "Beseelung der Quelle", 8, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 3);
    public static final O \u00f5\u00d2\u00f4000 = new O("Preisahnung", "Xolovar", "Analyse", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 20);
    public static final O \u00d5\u00d8\u00f4000 = new O("Infektion mit t\u00f6dlicher Krankheit", "Mishkarya", "Infektion", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d300000, 200);
    public static final O \u00d3\u00f6\u00d8000 = new O("Krankheit heilen", "Mishkarya", "Infektion", 3, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 2400);
    public static final O \u00f8\u00d8\u00f4000 = new O("Masseninfektion", "Mishkarya", "Infektion", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O nullObjectString = new O("Parasitenreinigung", "Mishkarya", "Kontrolle \u00fcber Wesen", 13, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 200);
    public static final O whilenewString = new O("Ungezieferbann", "Mishkarya", "Kontrolle \u00fcber Wesen", 16, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 200);
    public static final O returnStringString = new O("Berufskenntnisse (Grobschmied)", "Aggari", "Beseelung der Quelle", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 200);
    public static final O O\u00d3\u00f4000 = new O("D\u00e4monische Aufwertung", "Aggari", "Beseelung der Quelle", 8, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 2400);
    public static final O thisfloatString = new O("Goldmacher", "Aggari", "Elementare Reinheit", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d200000, 200);
    public static final O \u00f8\u00d8\u00d8000 = new O("Lange Aufwertung", "Aggari", "Elementare Reinheit", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 28800);
    public static final O nullfloatString = new O("Alte Freunde", "Darcalya", "Kontrolle \u00fcber Gef\u00fchle", 6, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 3);
    public static final O o\u00d6\u00f4000 = new O("Drogenrausch", "Darcalya", "Beseelung der Quelle", 5, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d500000, 5);
    public static final O \u00d5\u00f5\u00d8000 = new O("Gute Freunde", "Darcalya", "Kontrolle \u00fcber Gef\u00fchle", 7, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00f500000, 10);
    public static final O \u00d8\u00d5\u00f4000 = new O("K\u00fchler Kopf", "Darcalya", "Kontrolle \u00fcber Gef\u00fchle", 4, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.\u00d800000, 5);
    public static final O \u00d3\u00f8\u00d8000 = new O("Orgie", "Darcalya", "Beseelung der Quelle", 12, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0.null, 200);
    private static ArrayList<O> \u00f4\u00d8\u00f4000;
    private String whilereturnString;
    private o00O O\u00d8\u00d8000;
    private A nullvoidString;
    private int Oo\u00f4000;
    private oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0 O\u00f5\u00d8000;
    private Integer \u00f8\u00d2\u00f4000;

    public static ArrayList<O> O\u00f40000() {
        return \u00f4\u00d8\u00f4000;
    }

    public O(String string, o00O o00O2, A a2, int n, boolean bl, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0 oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_02, Integer n2) {
        try {
            this.whilereturnString = string;
            this.O\u00d8\u00d8000 = o00O2;
            this.nullvoidString = a2;
            this.Oo\u00f4000 = n;
            this.O\u00f5\u00d8000 = oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_02;
            this.\u00f8\u00d2\u00f4000 = n2;
            if (bl) {
                this.\u00f6\u00d80000();
            }
        }
        catch (Exception exception) {
            oooo_0.o00000(exception);
        }
    }

    public O(String string, String string2, String string3, int n) {
        this(string, string2, string3, n, null, null);
    }

    public O(String string, String string2, String string3, int n, boolean bl, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0 oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_02, Integer n2) {
        this(string, o00O.\u00d200000(string2), A.o00000(string3), n, bl, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_02, n2);
    }

    public O(String string, String string2, String string3, int n, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0 oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_02, Integer n2) {
        this(string, string2, string3, n, true, oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_02, n2);
    }

    public void \u00f6\u00d80000() {
        if (\u00f4\u00d8\u00f4000 == null) {
            \u00f4\u00d8\u00f4000 = new ArrayList();
        }
        if (!\u00f4\u00d8\u00f4000.contains(this)) {
            \u00f4\u00d8\u00f4000.add(this);
        }
    }

    public boolean equals(Object object) {
        if (this == object) {
            return true;
        }
        if (object == null) {
            return false;
        }
        if (this.getClass() != object.getClass()) {
            return false;
        }
        O o = (O)object;
        return this.hashCode() == o.hashCode();
    }

    public A \u00d5\u00d80000() {
        return this.nullvoidString;
    }

    public oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_0 \u00d6\u00d80000() {
        return this.O\u00f5\u00d8000;
    }

    public String interfaceclass() {
        return this.whilereturnString;
    }

    public int \u00f5\u00d80000() {
        return this.Oo\u00f4000;
    }

    public o00O \u00f4\u00d80000() {
        return this.O\u00d8\u00d8000;
    }

    public Integer doclass() {
        return this.\u00f8\u00d2\u00f4000;
    }

    public int hashCode() {
        int n = 1;
        n = 31 * n + (this.nullvoidString == null ? 0 : this.nullvoidString.hashCode());
        n = 31 * n + (this.whilereturnString == null ? 0 : this.whilereturnString.hashCode());
        n = 31 * n + this.Oo\u00f4000;
        n = 31 * n + (this.O\u00d8\u00d8000 == null ? 0 : this.O\u00d8\u00d8000.hashCode());
        if (this.\u00f8\u00d2\u00f4000 != null) {
            n = 31 * n + this.\u00f8\u00d2\u00f4000;
        }
        if (this.O\u00f5\u00d8000 != null) {
            n = 31 * n + this.O\u00f5\u00d8000.name().hashCode();
        }
        return n;
    }

    @Override
    public boolean istIntern() {
        return true;
    }

    public String toString() {
        return this.whilereturnString;
    }
}

